"""
Comprehensive emoji data based on Unicode 15.0 standard.

Each emoji entry: (emoji, keywords, text_representations)
Organized by Unicode categories for better organization.
"""

# Smileys & Emotion
SMILEYS_AND_EMOTION = [
    # Happy faces
    ("😀", ["grinning", "smile", "happy", "face"], [":D", ":-D"]),
    ("😃", ["smiley", "smile", "happy", "joy"], [":)", ":-)"]),
    ("😄", ["smile", "happy", "laugh", "grin"], []),
    ("😁", ["grin", "happy", "beaming"], []),
    ("😆", ["laugh", "satisfied", "happy", "squint"], []),
    ("😅", ["laugh", "nervous", "sweat", "grin"], []),
    ("🤣", ["rofl", "laugh", "rolling", "floor"], [":rofl:"]),
    ("😂", ["tears", "laugh", "joy", "crying"], []),
    ("🙂", ["smile", "happy", "slightly"], []),
    ("🙃", ["upside", "down", "silly", "face"], []),
    ("🫠", ["melting", "liquid", "hot"], []),
    ("😉", ["wink", "flirt", "hint"], [";)", ";-)"]),
    ("😊", ["blush", "smile", "happy", "eyes"], ["^^", "^_^"]),
    ("😇", ["angel", "innocent", "halo", "saint"], ["O:)", "O:-)"]),

    # Affection
    ("🥰", ["love", "hearts", "happy", "smiling"], []),
    ("😍", ["love", "heart", "eyes", "star"], []),
    ("🤩", ["star", "eyes", "excited", "struck"], []),
    ("😘", ["kiss", "love", "blowing"], [":*", ":-*"]),
    ("😗", ["kiss", "whistle", "kissing"], []),
    ("☺️", ["smile", "blush", "relaxed"], []),
    ("😚", ["kiss", "closed", "eyes", "kissing"], []),
    ("😙", ["kiss", "smile", "smiling"], []),
    ("🥲", ["smile", "tear", "happy", "sad"], []),

    # Tongue
    ("😋", ["yum", "delicious", "tongue", "savoring"], []),
    ("😛", ["tongue", "playful", "out"], [":P", ":-P"]),
    ("😜", ["tongue", "wink", "playful", "eye"], [";P", ";-P"]),
    ("🤪", ["crazy", "wild", "goofy", "zany"], []),
    ("😝", ["tongue", "wink", "playful", "squint"], []),
    ("🤑", ["money", "mouth", "rich", "dollar"], []),

    # Hand covering mouth
    ("🤗", ["hug", "embrace", "hugging"], []),
    ("🤭", ["giggle", "oops", "hand", "mouth"], []),
    ("🫢", ["gasp", "surprise", "eyes", "hand"], []),
    ("🫣", ["peek", "shy", "eyes", "hand"], []),
    ("🤫", ["shh", "quiet", "silence", "shush"], []),
    ("🤔", ["thinking", "hmm", "chin", "hand"], []),
    ("🫡", ["salute", "military", "respect"], []),

    # Skeptical
    ("🤐", ["zipper", "mouth", "shut", "sealed"], []),
    ("🤨", ["raised", "eyebrow", "skeptical", "suspicious"], []),
    ("😐", ["neutral", "meh", "deadpan"], [":|", ":-|"]),
    ("😑", ["expressionless", "unamused", "straight"], []),
    ("😶", ["blank", "no", "mouth", "silence"], []),
    ("🫥", ["dotted", "invisible", "disappear"], []),
    ("😶‍🌫️", ["fog", "clouds", "mist"], []),
    ("😏", ["smirk", "sly", "smug"], [":smirk:"]),
    ("😒", ["unamused", "annoyed", "unhappy"], []),
    ("🙄", ["roll", "eyes", "rolling"], []),
    ("😬", ["grimace", "awkward", "eek"], []),
    ("😮‍💨", ["exhale", "sigh", "relief"], []),
    ("🤥", ["liar", "pinocchio", "lying"], []),
    ("🫨", ["shake", "vibrate", "shaking"], []),

    # Sleepy
    ("😌", ["relieved", "calm", "content"], []),
    ("😔", ["pensive", "sad", "dejected"], []),
    ("😪", ["sleepy", "tired", "drowsy"], []),
    ("🤤", ["drool", "sleep", "drooling"], []),
    ("😴", ["sleep", "zzz", "sleeping"], []),

    # Unwell
    ("😷", ["mask", "sick", "ill", "medical"], []),
    ("🤒", ["thermometer", "sick", "ill", "fever"], []),
    ("🤕", ["bandage", "hurt", "injury", "head"], []),
    ("🤢", ["nausea", "sick", "vomit", "green"], []),
    ("🤮", ["vomit", "sick", "puke", "throw"], []),
    ("🤧", ["sneeze", "sick", "tissue", "achoo"], []),
    ("🥵", ["hot", "sweat", "heat"], []),
    ("🥶", ["cold", "freeze", "freezing", "ice"], []),
    ("🥴", ["woozy", "drunk", "dizzy", "intoxicated"], []),
    ("😵", ["dizzy", "confused", "crossed"], ["x_x", "X_X"]),
    ("😵‍💫", ["spiral", "hypnotized", "dizzy"], []),
    ("🤯", ["mind", "blown", "explode", "head"], []),

    # Hat faces
    ("🤠", ["cowboy", "hat", "western"], []),
    ("🥳", ["party", "celebrate", "hat", "horn"], []),
    ("🥸", ["disguise", "glasses", "nose", "incognito"], []),

    # Glasses
    ("😎", ["cool", "sunglasses", "awesome"], ["8)", "8-)", "B)", "B-)"]),
    ("🤓", ["nerd", "geek", "glasses", "smart"], []),
    ("🧐", ["monocle", "thinking", "suspicious"], []),

    # Concerned
    ("😕", ["confused", "uncertain", "puzzled"], []),
    ("🫤", ["diagonal", "mouth", "meh", "unsure"], []),
    ("😟", ["worried", "sad", "frown"], []),
    ("🙁", ["frown", "sad", "slightly"], []),
    ("☹️", ["frown", "sad", "unhappy"], []),
    ("😮", ["open", "mouth", "surprised", "oh"], []),
    ("😯", ["surprised", "shocked", "hushed"], [":o", ":-o", ":O", ":-O"]),
    ("😲", ["astonished", "shocked", "amazed"], []),
    ("😳", ["flushed", "surprised", "embarrassed"], []),
    ("🥺", ["pleading", "puppy", "eyes", "begging"], []),
    ("🥹", ["tear", "grateful", "proud", "touched"], []),
    ("😦", ["frown", "surprised", "open"], []),
    ("😧", ["anguished", "shocked", "stunned"], []),
    ("😨", ["fearful", "scared", "frightened"], []),
    ("😰", ["anxious", "nervous", "sweat", "blue"], []),
    ("😥", ["sad", "relieved", "tear", "disappointed"], []),
    ("😢", ["cry", "sad", "tear", "crying"], [":'(", "T_T"]),
    ("😭", ["crying", "sad", "tears", "loudly"], []),
    ("😱", ["scream", "scared", "munch", "fear"], []),
    ("😖", ["confounded", "frustrated", "confused"], []),
    ("😣", ["persevere", "struggle", "helpless"], []),
    ("😞", ["disappointed", "sad", "down"], []),
    ("😓", ["sweat", "nervous", "downcast"], []),
    ("😩", ["weary", "tired", "exhausted"], []),
    ("😫", ["tired", "exhausted", "fed", "up"], []),
    ("🥱", ["yawn", "tired", "bored", "sleepy"], []),

    # Negative
    ("😤", ["triumph", "frustrated", "mad", "steam"], []),
    ("😡", ["rage", "angry", "mad", "pouting"], []),
    ("😠", ["angry", "mad", "annoyed"], [">:(", ">:-("]),
    ("🤬", ["cursing", "swear", "angry", "symbols"], []),
    ("😈", ["devil", "evil", "horns", "smiling"], []),
    ("👿", ["devil", "evil", "angry", "imp"], []),
    ("💀", ["skull", "dead", "death"], []),
    ("☠️", ["skull", "crossbones", "poison", "death"], []),

    # Costume
    ("💩", ["poop", "pile", "poo", "shit"], []),
    ("🤡", ["clown", "joker", "circus"], []),
    ("👹", ["ogre", "monster", "japanese", "oni"], []),
    ("👺", ["goblin", "monster", "japanese", "tengu"], []),
    ("👻", ["ghost", "halloween", "boo"], []),
    ("👽", ["alien", "ufo", "space", "extraterrestrial"], []),
    ("👾", ["alien", "monster", "space", "invader"], []),
    ("🤖", ["robot", "bot", "android"], []),

    # Cat & Monkey faces
    ("😺", ["cat", "smile", "happy", "grinning"], []),
    ("😸", ["cat", "smile", "happy", "grin"], []),
    ("😹", ["cat", "laugh", "joy", "tears"], []),
    ("😻", ["cat", "love", "heart", "eyes"], []),
    ("😼", ["cat", "smirk", "wry"], []),
    ("😽", ["cat", "kiss", "kissing"], []),
    ("🙀", ["cat", "scared", "scream", "weary"], []),
    ("😿", ["cat", "cry", "sad", "tear"], []),
    ("😾", ["cat", "angry", "pouting"], []),

    # Monkey faces
    ("🙈", ["monkey", "see", "no", "evil"], []),
    ("🙉", ["monkey", "hear", "no", "evil"], []),
    ("🙊", ["monkey", "speak", "no", "evil"], []),

    # Hearts
    ("💌", ["love", "letter", "heart", "mail"], []),
    ("💘", ["cupid", "arrow", "love", "heart"], []),
    ("💝", ["heart", "ribbon", "gift", "box"], []),
    ("💖", ["sparkling", "heart", "sparkle", "love"], []),
    ("💗", ["growing", "heart", "love", "excited"], []),
    ("💓", ["beating", "heart", "love", "heartbeat"], []),
    ("💞", ["revolving", "hearts", "love", "two"], []),
    ("💕", ["two", "hearts", "love", "affection"], []),
    ("💟", ["heart", "decoration", "love", "purple"], []),
    ("❣️", ["exclamation", "heart", "love", "mark"], []),
    ("💔", ["broken", "heart", "sad", "break"], ["</3"]),
    ("❤️‍🔥", ["fire", "heart", "love", "burning"], []),
    ("❤️‍🩹", ["healing", "heart", "mending", "bandage"], []),
    ("❤️", ["heart", "love", "red"], ["<3"]),
    ("🩷", ["pink", "heart", "love", "cute"], []),
    ("🧡", ["orange", "heart", "love"], []),
    ("💛", ["yellow", "heart", "love"], []),
    ("💚", ["green", "heart", "love"], []),
    ("💙", ["blue", "heart", "love"], []),
    ("🩵", ["light", "blue", "heart", "love"], []),
    ("💜", ["purple", "heart", "love"], []),
    ("🤎", ["brown", "heart", "love"], []),
    ("🖤", ["black", "heart", "dark"], []),
    ("🩶", ["grey", "heart", "love"], []),
    ("🤍", ["white", "heart", "pure"], []),

    # Emotion
    ("💋", ["kiss", "lips", "love", "mark"], []),
    ("💯", ["hundred", "points", "perfect", "100"], []),
    ("💢", ["anger", "symbol", "mad", "comic"], []),
    ("💥", ["boom", "explosion", "collision"], []),
    ("💫", ["dizzy", "star", "sparkle"], []),
    ("💦", ["sweat", "droplets", "water"], []),
    ("💨", ["dash", "fast", "wind", "running"], []),
    ("🕳️", ["hole", "pit", "void"], []),
    ("💬", ["speech", "balloon", "talk", "comment"], []),
    ("👁️‍🗨️", ["eye", "speech", "bubble", "witness"], []),
    ("🗨️", ["speech", "balloon", "left", "talk"], []),
    ("🗯️", ["anger", "balloon", "right", "mad"], []),
    ("💭", ["thought", "balloon", "thinking", "bubble"], []),
    ("💤", ["zzz", "sleep", "sleeping", "tired"], []),
]

# People & Body
PEOPLE_AND_BODY = [
    # Hand gestures
    ("👋", ["wave", "hello", "bye", "hand"], []),
    ("🤚", ["raised", "back", "hand", "stop"], []),
    ("🖐️", ["hand", "fingers", "raised", "splayed"], []),
    ("✋", ["hand", "stop", "raised"], []),
    ("🖖", ["vulcan", "spock", "star", "trek"], []),
    ("🫱", ["right", "hand", "rightward"], []),
    ("🫲", ["left", "hand", "leftward"], []),
    ("🫳", ["palm", "down", "hand", "drop"], []),
    ("🫴", ["palm", "up", "hand", "offer"], []),
    ("🫷", ["push", "left", "hand"], []),
    ("🫸", ["push", "right", "hand"], []),
    ("👌", ["ok", "okay", "good", "perfect"], []),
    ("🤌", ["pinched", "fingers", "italian"], []),
    ("🤏", ["pinch", "small", "tiny"], []),
    ("✌️", ["peace", "victory", "v"], []),
    ("🤞", ["fingers", "crossed", "luck", "hope"], []),
    ("🫰", ["hand", "heart", "finger", "snap"], []),
    ("🤟", ["love", "you", "ily", "sign"], []),
    ("🤘", ["rock", "metal", "horns", "devil"], []),
    ("🤙", ["call", "hang", "loose", "shaka"], []),
    ("👈", ["point", "left", "finger", "backhand"], []),
    ("👉", ["point", "right", "finger", "backhand"], []),
    ("👆", ["point", "up", "finger", "backhand"], []),
    ("🖕", ["middle", "finger", "rude", "offensive"], []),
    ("👇", ["point", "down", "finger", "backhand"], []),
    ("☝️", ["point", "up", "finger", "index"], []),
    ("🫵", ["point", "you", "finger", "index"], []),
    ("👍", ["thumbs", "up", "yes", "good"], ["+1"]),
    ("👎", ["thumbs", "down", "no", "bad"], ["-1"]),
    ("✊", ["fist", "power", "raised", "solidarity"], []),
    ("👊", ["punch", "fist", "bump", "oncoming"], []),
    ("🤛", ["left", "fist", "bump", "facing"], []),
    ("🤜", ["right", "fist", "bump", "facing"], []),

    # Hands
    ("👏", ["clap", "applause", "hands", "clapping"], []),
    ("🙌", ["celebrate", "hands", "up", "raising"], []),
    ("🫶", ["heart", "hands", "love"], []),
    ("👐", ["open", "hands", "palms"], []),
    ("🤲", ["palms", "together", "up", "prayer"], []),
    ("🤝", ["handshake", "deal", "agreement", "shake"], []),
    ("🙏", ["pray", "thanks", "please", "folded"], []),

    # Hand props
    ("✍️", ["write", "pen", "writing", "hand"], []),
    ("💅", ["nail", "polish", "manicure", "care"], []),
    ("🤳", ["selfie", "camera", "phone"], []),

    # Body parts
    ("💪", ["muscle", "strong", "flex", "bicep"], []),
    ("🦾", ["robot", "arm", "mechanical", "prosthetic"], []),
    ("🦿", ["robot", "leg", "mechanical", "prosthetic"], []),
    ("🦵", ["leg", "kick", "limb"], []),
    ("🦶", ["foot", "kick", "stomp"], []),
    ("👂", ["ear", "hear", "listen"], []),
    ("🦻", ["ear", "hearing", "aid"], []),
    ("👃", ["nose", "smell", "scent"], []),
    ("🧠", ["brain", "smart", "intelligent"], []),
    ("🫀", ["heart", "organ", "anatomical"], []),
    ("🫁", ["lungs", "organ", "breathe"], []),
    ("🦷", ["tooth", "dentist", "dental"], []),
    ("🦴", ["bone", "skeleton"], []),
    ("👀", ["eyes", "look", "watch", "see"], []),
    ("👁️", ["eye", "see", "look"], []),
    ("👅", ["tongue", "taste", "lick"], []),
    ("👄", ["mouth", "lips", "kiss"], []),
    ("🫦", ["biting", "lip", "flirt", "anxious"], []),

    # Person
    ("👶", ["baby", "infant", "child"], []),
    ("🧒", ["child", "kid", "young"], []),
    ("👦", ["boy", "child", "male"], []),
    ("👧", ["girl", "child", "female"], []),
    ("🧑", ["person", "adult", "gender"], []),
    ("👱", ["person", "blond", "hair"], []),
    ("👨", ["man", "male", "adult"], []),
    ("🧔", ["man", "beard", "person"], []),
    ("🧔‍♂️", ["man", "beard", "male"], []),
    ("🧔‍♀️", ["woman", "beard", "female"], []),
    ("👨‍🦰", ["man", "red", "hair"], []),
    ("👨‍🦱", ["man", "curly", "hair"], []),
    ("👨‍🦳", ["man", "white", "hair"], []),
    ("👨‍🦲", ["man", "bald", "no", "hair"], []),
    ("👩", ["woman", "female", "adult"], []),
    ("👩‍🦰", ["woman", "red", "hair"], []),
    ("👩‍🦱", ["woman", "curly", "hair"], []),
    ("👩‍🦳", ["woman", "white", "hair"], []),
    ("👩‍🦲", ["woman", "bald", "no", "hair"], []),
    ("🧓", ["older", "person", "adult", "senior"], []),
    ("👴", ["old", "man", "senior", "elder"], []),
    ("👵", ["old", "woman", "senior", "elder"], []),

    # Person gesture
    ("🙍", ["person", "frown", "sad"], []),
    ("🙍‍♂️", ["man", "frown", "sad"], []),
    ("🙍‍♀️", ["woman", "frown", "sad"], []),
    ("🙎", ["person", "pouting", "angry"], []),
    ("🙎‍♂️", ["man", "pouting", "angry"], []),
    ("🙎‍♀️", ["woman", "pouting", "angry"], []),
    ("🙅", ["person", "no", "forbidden", "stop"], []),
    ("🙅‍♂️", ["man", "no", "forbidden"], []),
    ("🙅‍♀️", ["woman", "no", "forbidden"], []),
    ("🙆", ["person", "ok", "yes", "arms"], []),
    ("🙆‍♂️", ["man", "ok", "yes"], []),
    ("🙆‍♀️", ["woman", "ok", "yes"], []),
    ("💁", ["person", "tipping", "hand", "sassy"], []),
    ("💁‍♂️", ["man", "tipping", "hand"], []),
    ("💁‍♀️", ["woman", "tipping", "hand"], []),
    ("🙋", ["person", "raising", "hand", "question"], []),
    ("🙋‍♂️", ["man", "raising", "hand"], []),
    ("🙋‍♀️", ["woman", "raising", "hand"], []),
    ("🧏", ["deaf", "person", "ear", "hear"], []),
    ("🧏‍♂️", ["deaf", "man", "ear"], []),
    ("🧏‍♀️", ["deaf", "woman", "ear"], []),
    ("🙇", ["person", "bowing", "sorry", "apologize"], []),
    ("🙇‍♂️", ["man", "bowing", "sorry"], []),
    ("🙇‍♀️", ["woman", "bowing", "sorry"], []),
    ("🤦", ["facepalm", "person", "disappointed"], []),
    ("🤦‍♂️", ["man", "facepalm", "disappointed"], []),
    ("🤦‍♀️", ["woman", "facepalm", "disappointed"], []),
    ("🤷", ["shrug", "person", "doubt", "idk"], []),
    ("🤷‍♂️", ["man", "shrug", "doubt"], []),
    ("🤷‍♀️", ["woman", "shrug", "doubt"], []),
]

# Animals & Nature
ANIMALS_AND_NATURE = [
    # Mammals
    ("🐵", ["monkey", "face", "animal"], []),
    ("🐒", ["monkey", "animal", "primate"], []),
    ("🦍", ["gorilla", "animal", "ape"], []),
    ("🦧", ["orangutan", "animal", "ape"], []),
    ("🐶", ["dog", "face", "pet", "puppy"], []),
    ("🐕", ["dog", "pet", "animal"], []),
    ("🦮", ["guide", "dog", "service", "blind"], []),
    ("🐕‍🦺", ["service", "dog", "assistance"], []),
    ("🐩", ["poodle", "dog", "pet"], []),
    ("🐺", ["wolf", "face", "animal"], []),
    ("🦊", ["fox", "face", "animal"], []),
    ("🦝", ["raccoon", "animal", "curious"], []),
    ("🐱", ["cat", "face", "pet", "kitten"], []),
    ("🐈", ["cat", "pet", "animal"], []),
    ("🐈‍⬛", ["black", "cat", "superstition"], []),
    ("🦁", ["lion", "face", "king", "animal"], []),
    ("🐯", ["tiger", "face", "animal"], []),
    ("🐅", ["tiger", "animal", "big", "cat"], []),
    ("🐆", ["leopard", "animal", "big", "cat"], []),
    ("🐴", ["horse", "face", "animal"], []),
    ("🫎", ["moose", "animal", "antlers"], []),
    ("🫏", ["donkey", "animal", "mule"], []),
    ("🐎", ["horse", "racing", "animal"], []),
    ("🦄", ["unicorn", "fantasy", "magical"], []),
    ("🦓", ["zebra", "animal", "stripes"], []),
    ("🦌", ["deer", "animal", "antlers"], []),
    ("🦬", ["bison", "animal", "buffalo"], []),
    ("🐮", ["cow", "face", "animal"], []),
    ("🐂", ["ox", "animal", "bull"], []),
    ("🐃", ["water", "buffalo", "animal"], []),
    ("🐄", ["cow", "animal", "dairy"], []),
    ("🐷", ["pig", "face", "animal"], []),
    ("🐖", ["pig", "animal", "pork"], []),
    ("🐗", ["boar", "pig", "animal"], []),
    ("🐽", ["pig", "nose", "snout"], []),
    ("🐏", ["ram", "sheep", "animal"], []),
    ("🐑", ["ewe", "sheep", "animal"], []),
    ("🐐", ["goat", "animal", "capricorn"], []),
    ("🐪", ["camel", "dromedary", "desert"], []),
    ("🐫", ["camel", "bactrian", "two", "hump"], []),
    ("🦙", ["llama", "animal", "guanaco"], []),
    ("🦒", ["giraffe", "animal", "tall"], []),
    ("🐘", ["elephant", "animal", "large"], []),
    ("🦣", ["mammoth", "elephant", "extinct"], []),
    ("🦏", ["rhino", "rhinoceros", "animal"], []),
    ("🦛", ["hippo", "hippopotamus", "animal"], []),
    ("🐭", ["mouse", "face", "animal"], []),
    ("🐁", ["mouse", "animal", "rodent"], []),
    ("🐀", ["rat", "animal", "rodent"], []),
    ("🐹", ["hamster", "face", "pet"], []),
    ("🐰", ["rabbit", "face", "bunny", "pet"], []),
    ("🐇", ["rabbit", "bunny", "animal"], []),
    ("🐿️", ["chipmunk", "squirrel", "animal"], []),
    ("🦫", ["beaver", "animal", "dam"], []),
    ("🦔", ["hedgehog", "animal", "spiny"], []),
    ("🦇", ["bat", "vampire", "animal"], []),
    ("🐻", ["bear", "face", "animal"], []),
    ("🐻‍❄️", ["polar", "bear", "white", "arctic"], []),
    ("🐨", ["koala", "animal", "australia"], []),
    ("🐼", ["panda", "face", "animal"], []),
    ("🦥", ["sloth", "lazy", "slow", "animal"], []),
    ("🦦", ["otter", "animal", "playful"], []),
    ("🦨", ["skunk", "animal", "stink"], []),
    ("🦘", ["kangaroo", "animal", "australia"], []),
    ("🦡", ["badger", "animal", "honey"], []),

    # Birds
    ("🐾", ["paw", "prints", "animal", "feet"], []),
    ("🦃", ["turkey", "bird", "thanksgiving"], []),
    ("🐔", ["chicken", "bird", "rooster"], []),
    ("🐓", ["rooster", "bird", "morning"], []),
    ("🐣", ["hatching", "chick", "bird", "egg"], []),
    ("🐤", ["baby", "chick", "bird", "small"], []),
    ("🐥", ["front", "chick", "bird", "baby"], []),
    ("🐦", ["bird", "animal", "fly"], []),
    ("🐧", ["penguin", "bird", "antarctica"], []),
    ("🕊️", ["dove", "peace", "bird"], []),
    ("🦅", ["eagle", "bird", "america"], []),
    ("🦆", ["duck", "bird", "animal"], []),
    ("🦢", ["swan", "bird", "elegant"], []),
    ("🦉", ["owl", "bird", "wise", "night"], []),
    ("🦤", ["dodo", "bird", "extinct"], []),
    ("🪶", ["feather", "bird", "light"], []),
    ("🦩", ["flamingo", "bird", "tropical"], []),
    ("🦚", ["peacock", "bird", "proud", "feathers"], []),
    ("🦜", ["parrot", "bird", "tropical", "talk"], []),
    ("🪽", ["wing", "bird", "fly", "angel"], []),
    ("🐦‍⬛", ["black", "bird", "crow", "raven"], []),
    ("🪿", ["goose", "bird", "honk"], []),

    # Reptiles & Amphibians
    ("🐸", ["frog", "face", "animal", "amphibian"], []),
    ("🐊", ["crocodile", "alligator", "animal"], []),
    ("🐢", ["turtle", "tortoise", "slow", "animal"], []),
    ("🦎", ["lizard", "reptile", "animal"], []),
    ("🐍", ["snake", "serpent", "reptile"], []),
    ("🐲", ["dragon", "face", "fantasy"], []),
    ("🐉", ["dragon", "fantasy", "mythical"], []),
    ("🦕", ["sauropod", "dinosaur", "extinct"], []),
    ("🦖", ["t-rex", "dinosaur", "extinct"], []),

    # Marine animals
    ("🐳", ["whale", "spouting", "ocean", "sea"], []),
    ("🐋", ["whale", "ocean", "sea", "large"], []),
    ("🐬", ["dolphin", "ocean", "sea", "flipper"], []),
    ("🦭", ["seal", "animal", "sea"], []),
    ("🐟", ["fish", "animal", "sea"], []),
    ("🐠", ["tropical", "fish", "ocean", "colorful"], []),
    ("🐡", ["blowfish", "fish", "ocean", "puffer"], []),
    ("🦈", ["shark", "fish", "ocean", "dangerous"], []),
    ("🐙", ["octopus", "sea", "animal"], []),
    ("🐚", ["shell", "spiral", "beach", "sea"], []),
    ("🪸", ["coral", "ocean", "reef"], []),
    ("🪼", ["jellyfish", "ocean", "sea"], []),

    # Bugs
    ("🐌", ["snail", "slow", "shell", "animal"], []),
    ("🦋", ["butterfly", "insect", "beautiful"], []),
    ("🐛", ["bug", "insect", "caterpillar"], []),
    ("🐜", ["ant", "insect", "small"], []),
    ("🐝", ["bee", "honeybee", "insect"], []),
    ("🪲", ["beetle", "insect", "bug"], []),
    ("🐞", ["ladybug", "beetle", "insect"], []),
    ("🦗", ["cricket", "insect", "grasshopper"], []),
    ("🪳", ["cockroach", "insect", "bug"], []),
    ("🕷️", ["spider", "insect", "arachnid"], []),
    ("🕸️", ["spider", "web", "silk"], []),
    ("🦂", ["scorpion", "zodiac", "dangerous"], []),
    ("🦟", ["mosquito", "insect", "bite"], []),
    ("🪰", ["fly", "insect", "pest"], []),
    ("🪱", ["worm", "earthworm", "parasite"], []),
    ("🦠", ["microbe", "germ", "bacteria", "virus"], []),

    # Flowers
    ("💐", ["bouquet", "flowers", "gift"], []),
    ("🌸", ["cherry", "blossom", "flower", "spring"], []),
    ("💮", ["white", "flower", "japanese"], []),
    ("🪷", ["lotus", "flower", "purity"], []),
    ("🏵️", ["rosette", "flower", "award"], []),
    ("🌹", ["rose", "flower", "romantic"], []),
    ("🥀", ["wilted", "flower", "dead", "sad"], []),
    ("🌺", ["hibiscus", "flower", "tropical"], []),
    ("🌻", ["sunflower", "flower", "yellow"], []),
    ("🌼", ["blossom", "flower", "daisy"], []),
    ("🌷", ["tulip", "flower", "spring"], []),
    ("🪻", ["hyacinth", "flower", "purple"], []),

    # Plants
    ("🌱", ["seedling", "plant", "new", "sprout"], []),
    ("🪴", ["potted", "plant", "houseplant"], []),
    ("🌲", ["evergreen", "tree", "pine"], []),
    ("🌳", ["deciduous", "tree", "nature"], []),
    ("🌴", ["palm", "tree", "tropical"], []),
    ("🌵", ["cactus", "desert", "plant"], []),
    ("🌾", ["sheaf", "rice", "grain"], []),
    ("🌿", ["herb", "leaf", "plant"], []),
    ("☘️", ["shamrock", "plant", "lucky", "irish"], []),
    ("🍀", ["four", "leaf", "clover", "lucky"], []),
    ("🍁", ["maple", "leaf", "canada", "autumn"], []),
    ("🍂", ["fallen", "leaf", "autumn", "leaves"], []),
    ("🍃", ["leaf", "fluttering", "wind", "blow"], []),
    ("🪹", ["nest", "eggs", "bird"], []),
    ("🪺", ["nest", "with", "eggs"], []),
    ("🍄", ["mushroom", "toadstool", "fungi"], []),
]

# Food & Drink
FOOD_AND_DRINK = [
    # Fruit
    ("🍇", ["grapes", "fruit", "wine"], []),
    ("🍈", ["melon", "fruit", "cantaloupe"], []),
    ("🍉", ["watermelon", "fruit", "summer"], []),
    ("🍊", ["orange", "tangerine", "fruit"], []),
    ("🍋", ["lemon", "fruit", "citrus"], []),
    ("🍌", ["banana", "fruit", "yellow"], []),
    ("🍍", ["pineapple", "fruit", "tropical"], []),
    ("🥭", ["mango", "fruit", "tropical"], []),
    ("🍎", ["red", "apple", "fruit"], []),
    ("🍏", ["green", "apple", "fruit"], []),
    ("🍐", ["pear", "fruit"], []),
    ("🍑", ["peach", "fruit", "butt"], []),
    ("🍒", ["cherries", "fruit", "red"], []),
    ("🍓", ["strawberry", "fruit", "berry"], []),
    ("🫐", ["blueberries", "fruit", "berry"], []),
    ("🥝", ["kiwi", "fruit", "green"], []),
    ("🍅", ["tomato", "vegetable", "fruit"], []),
    ("🫒", ["olive", "food", "mediterranean"], []),
    ("🥥", ["coconut", "fruit", "tropical"], []),

    # Vegetables
    ("🥑", ["avocado", "fruit", "vegetable"], []),
    ("🍆", ["eggplant", "vegetable", "aubergine"], []),
    ("🥔", ["potato", "vegetable", "food"], []),
    ("🥕", ["carrot", "vegetable", "food"], []),
    ("🌽", ["corn", "maize", "ear"], []),
    ("🌶️", ["hot", "pepper", "spicy", "chili"], []),
    ("🫑", ["bell", "pepper", "vegetable"], []),
    ("🥒", ["cucumber", "vegetable", "pickle"], []),
    ("🥬", ["leafy", "green", "bok", "choy"], []),
    ("🥦", ["broccoli", "vegetable", "green"], []),
    ("🧄", ["garlic", "vegetable", "flavor"], []),
    ("🧅", ["onion", "vegetable", "flavor"], []),
    ("🥜", ["peanuts", "nuts", "food"], []),
    ("🫘", ["beans", "legume", "food"], []),
    ("🌰", ["chestnut", "nut", "food"], []),
    ("🫚", ["ginger", "root", "spice"], []),
    ("🫛", ["pea", "pod", "vegetable"], []),
    ("🍄‍🟫", ["brown", "mushroom", "fungi"], []),

    # Prepared food
    ("🍞", ["bread", "loaf", "food"], []),
    ("🥐", ["croissant", "bread", "french"], []),
    ("🥖", ["baguette", "bread", "french"], []),
    ("🫓", ["flatbread", "pita", "lavash"], []),
    ("🥨", ["pretzel", "bread", "twisted"], []),
    ("🥯", ["bagel", "bread", "food"], []),
    ("🥞", ["pancakes", "breakfast", "food"], []),
    ("🧇", ["waffle", "breakfast", "food"], []),
    ("🧀", ["cheese", "wedge", "food"], []),
    ("🍖", ["meat", "bone", "food"], []),
    ("🍗", ["poultry", "leg", "chicken"], []),
    ("🥩", ["cut", "meat", "steak"], []),
    ("🥓", ["bacon", "meat", "breakfast"], []),
    ("🍔", ["hamburger", "burger", "food"], []),
    ("🍟", ["fries", "french", "potato"], []),
    ("🍕", ["pizza", "slice", "food"], []),
    ("🌭", ["hot", "dog", "sausage"], []),
    ("🥪", ["sandwich", "bread", "food"], []),
    ("🌮", ["taco", "mexican", "food"], []),
    ("🌯", ["burrito", "wrap", "food"], []),
    ("🫔", ["tamale", "mexican", "food"], []),
    ("🥙", ["stuffed", "flatbread", "gyro"], []),
    ("🧆", ["falafel", "chickpea", "food"], []),
    ("🥚", ["egg", "food", "breakfast"], []),
    ("🍳", ["cooking", "egg", "fried"], []),
    ("🥘", ["paella", "shallow", "pan"], []),
    ("🍲", ["pot", "food", "stew"], []),
    ("🫕", ["fondue", "cheese", "pot"], []),
    ("🥣", ["bowl", "spoon", "cereal"], []),
    ("🥗", ["green", "salad", "healthy"], []),
    ("🍿", ["popcorn", "snack", "movie"], []),
    ("🧈", ["butter", "dairy", "food"], []),
    ("🧂", ["salt", "shaker", "seasoning"], []),
    ("🥫", ["canned", "food", "soup"], []),

    # Asian food
    ("🍱", ["bento", "box", "japanese"], []),
    ("🍘", ["rice", "cracker", "japanese"], []),
    ("🍙", ["rice", "ball", "onigiri"], []),
    ("🍚", ["cooked", "rice", "food"], []),
    ("🍛", ["curry", "rice", "food"], []),
    ("🍜", ["steaming", "bowl", "ramen"], []),
    ("🍝", ["spaghetti", "pasta", "food"], []),
    ("🍠", ["roasted", "sweet", "potato"], []),
    ("🍢", ["oden", "skewer", "japanese"], []),
    ("🍣", ["sushi", "japanese", "food"], []),
    ("🍤", ["fried", "shrimp", "tempura"], []),
    ("🍥", ["fish", "cake", "swirl"], []),
    ("🥮", ["moon", "cake", "chinese"], []),
    ("🍡", ["dango", "dessert", "japanese"], []),
    ("🥟", ["dumpling", "food", "gyoza"], []),
    ("🥠", ["fortune", "cookie", "prophecy"], []),
    ("🥡", ["takeout", "box", "oyster"], []),

    # Sweets
    ("🦀", ["crab", "seafood", "cancer"], []),
    ("🦞", ["lobster", "seafood", "food"], []),
    ("🦐", ["shrimp", "seafood", "small"], []),
    ("🦑", ["squid", "seafood", "food"], []),
    ("🦪", ["oyster", "seafood", "pearl"], []),
    ("🍦", ["soft", "ice", "cream"], []),
    ("🍧", ["shaved", "ice", "dessert"], []),
    ("🍨", ["ice", "cream", "dessert"], []),
    ("🍩", ["doughnut", "donut", "sweet"], []),
    ("🍪", ["cookie", "sweet", "snack"], []),
    ("🎂", ["birthday", "cake", "celebration"], []),
    ("🍰", ["shortcake", "cake", "dessert"], []),
    ("🧁", ["cupcake", "sweet", "dessert"], []),
    ("🥧", ["pie", "dessert", "filling"], []),
    ("🍫", ["chocolate", "bar", "sweet"], []),
    ("🍬", ["candy", "sweet", "wrapped"], []),
    ("🍭", ["lollipop", "candy", "sweet"], []),
    ("🍮", ["custard", "pudding", "dessert"], []),
    ("🍯", ["honey", "pot", "sweet"], []),

    # Drinks
    ("🍼", ["baby", "bottle", "milk"], []),
    ("🥛", ["milk", "glass", "dairy"], []),
    ("☕", ["coffee", "hot", "beverage"], []),
    ("🫖", ["teapot", "tea", "drink"], []),
    ("🍵", ["teacup", "tea", "green"], []),
    ("🍶", ["sake", "bottle", "cup"], []),
    ("🍾", ["champagne", "bottle", "popping"], []),
    ("🍷", ["wine", "glass", "red"], []),
    ("🍸", ["cocktail", "glass", "drink"], []),
    ("🍹", ["tropical", "drink", "cocktail"], []),
    ("🍺", ["beer", "mug", "drink"], []),
    ("🍻", ["beers", "clinking", "cheers"], []),
    ("🥂", ["clinking", "glasses", "cheers"], []),
    ("🥃", ["tumbler", "glass", "whisky"], []),
    ("🫗", ["pouring", "liquid", "glass"], []),
    ("🥤", ["cup", "straw", "soda"], []),
    ("🧋", ["bubble", "tea", "boba"], []),
    ("🧃", ["beverage", "box", "juice"], []),
    ("🧉", ["mate", "drink", "yerba"], []),
    ("🧊", ["ice", "cube", "cold"], []),

    # Dishware
    ("🥢", ["chopsticks", "utensils", "asian"], []),
    ("🍽️", ["fork", "knife", "plate"], []),
    ("🍴", ["fork", "knife", "utensils"], []),
    ("🥄", ["spoon", "utensil", "food"], []),
    ("🔪", ["knife", "kitchen", "cut"], []),
    ("🫙", ["jar", "container", "empty"], []),
    ("🏺", ["amphora", "jar", "vase"], []),
]

# Travel & Places
TRAVEL_AND_PLACES = [
    # Map symbols
    ("🌍", ["globe", "europe", "africa", "earth"], []),
    ("🌎", ["globe", "americas", "earth"], []),
    ("🌏", ["globe", "asia", "australia", "earth"], []),
    ("🌐", ["globe", "meridians", "world", "internet"], []),
    ("🗺️", ["map", "world", "navigation"], []),
    ("🗾", ["japan", "map", "island"], []),
    ("🧭", ["compass", "navigation", "direction"], []),

    # Mountains & Geography
    ("🏔️", ["mountain", "snow", "peak"], []),
    ("⛰️", ["mountain", "peak", "nature"], []),
    ("🌋", ["volcano", "eruption", "lava"], []),
    ("🗻", ["mount", "fuji", "mountain"], []),
    ("🏕️", ["camping", "tent", "outdoors"], []),
    ("🏖️", ["beach", "umbrella", "vacation"], []),
    ("🏜️", ["desert", "sand", "hot"], []),
    ("🏝️", ["island", "desert", "palm"], []),
    ("🏞️", ["park", "national", "nature"], []),

    # Buildings
    ("🏟️", ["stadium", "arena", "sports"], []),
    ("🏛️", ["classical", "building", "museum"], []),
    ("🏗️", ["construction", "building", "crane"], []),
    ("🧱", ["brick", "wall", "construction"], []),
    ("🪨", ["rock", "stone", "boulder"], []),
    ("🪵", ["wood", "log", "lumber"], []),
    ("🛖", ["hut", "house", "dwelling"], []),
    ("🏘️", ["houses", "buildings", "neighborhood"], []),
    ("🏚️", ["derelict", "house", "abandoned"], []),
    ("🏠", ["house", "home", "building"], []),
    ("🏡", ["house", "garden", "home"], []),
    ("🏢", ["office", "building", "work"], []),
    ("🏣", ["post", "office", "japanese"], []),
    ("🏤", ["post", "office", "european"], []),
    ("🏥", ["hospital", "doctor", "health"], []),
    ("🏦", ["bank", "money", "finance"], []),
    ("🏨", ["hotel", "accommodation", "building"], []),
    ("🏩", ["love", "hotel", "japanese"], []),
    ("🏪", ["convenience", "store", "shop"], []),
    ("🏫", ["school", "education", "building"], []),
    ("🏬", ["department", "store", "shopping"], []),
    ("🏭", ["factory", "industrial", "building"], []),
    ("🏯", ["castle", "japanese", "fortress"], []),
    ("🏰", ["castle", "european", "fortress"], []),
    ("💒", ["wedding", "marriage", "chapel"], []),
    ("🗼", ["tokyo", "tower", "landmark"], []),
    ("🗽", ["liberty", "statue", "new", "york"], []),

    # Religious buildings
    ("⛪", ["church", "christian", "religion"], []),
    ("🕌", ["mosque", "islam", "religion"], []),
    ("🛕", ["hindu", "temple", "religion"], []),
    ("🕍", ["synagogue", "jewish", "religion"], []),
    ("⛩️", ["shinto", "shrine", "japanese"], []),
    ("🕋", ["kaaba", "mecca", "islam"], []),

    # Other places
    ("⛲", ["fountain", "water", "park"], []),
    ("⛺", ["tent", "camping", "outdoors"], []),
    ("🌁", ["foggy", "fog", "weather"], []),
    ("🌃", ["night", "stars", "city"], []),
    ("🏙️", ["cityscape", "skyline", "buildings"], []),
    ("🌄", ["sunrise", "mountains", "morning"], []),
    ("🌅", ["sunrise", "morning", "sun"], []),
    ("🌆", ["cityscape", "dusk", "sunset"], []),
    ("🌇", ["sunset", "dusk", "city"], []),
    ("🌉", ["bridge", "night", "san", "francisco"], []),
    ("♨️", ["hot", "springs", "onsen"], []),
    ("🎠", ["carousel", "horse", "merry"], []),
    ("🛝", ["playground", "slide", "park"], []),
    ("🎡", ["ferris", "wheel", "amusement"], []),
    ("🎢", ["roller", "coaster", "amusement"], []),
    ("💈", ["barber", "pole", "haircut"], []),
    ("🎪", ["circus", "tent", "entertainment"], []),

    # Transportation - Land
    ("🚂", ["locomotive", "train", "steam"], []),
    ("🚃", ["railway", "car", "train"], []),
    ("🚄", ["high", "speed", "train"], []),
    ("🚅", ["bullet", "train", "shinkansen"], []),
    ("🚆", ["train", "railway"], []),
    ("🚇", ["metro", "subway", "underground"], []),
    ("🚈", ["light", "rail", "train"], []),
    ("🚉", ["station", "train", "railway"], []),
    ("🚊", ["tram", "trolleybus", "streetcar"], []),
    ("🚝", ["monorail", "train", "railway"], []),
    ("🚞", ["mountain", "railway", "train"], []),
    ("🚋", ["tram", "car", "trolley"], []),
    ("🚌", ["bus", "vehicle", "transport"], []),
    ("🚍", ["oncoming", "bus", "front"], []),
    ("🚎", ["trolleybus", "bus", "electric"], []),
    ("🚐", ["minibus", "van", "vehicle"], []),
    ("🚑", ["ambulance", "emergency", "vehicle"], []),
    ("🚒", ["fire", "engine", "truck"], []),
    ("🚓", ["police", "car", "vehicle"], []),
    ("🚔", ["oncoming", "police", "car"], []),
    ("🚕", ["taxi", "cab", "vehicle"], []),
    ("🚖", ["oncoming", "taxi", "cab"], []),
    ("🚗", ["car", "automobile", "vehicle"], []),
    ("🚘", ["oncoming", "automobile", "car"], []),
    ("🚙", ["sport", "utility", "vehicle", "suv"], []),
    ("🛻", ["pickup", "truck", "vehicle"], []),
    ("🚚", ["delivery", "truck", "vehicle"], []),
    ("🚛", ["articulated", "lorry", "truck"], []),
    ("🚜", ["tractor", "vehicle", "farm"], []),
    ("🏎️", ["racing", "car", "fast"], []),
    ("🏍️", ["motorcycle", "racing", "bike"], []),
    ("🛵", ["motor", "scooter", "vespa"], []),
    ("🦽", ["manual", "wheelchair", "accessibility"], []),
    ("🦼", ["motorized", "wheelchair", "accessibility"], []),
    ("🛺", ["auto", "rickshaw", "tuk", "tuk"], []),
    ("🚲", ["bicycle", "bike", "cycle"], []),
    ("🛴", ["kick", "scooter", "vehicle"], []),
    ("🛹", ["skateboard", "board", "skate"], []),
    ("🛼", ["roller", "skate", "skating"], []),
    ("🚏", ["bus", "stop", "sign"], []),
    ("🛣️", ["motorway", "highway", "road"], []),
    ("🛤️", ["railway", "track", "train"], []),
    ("🛢️", ["oil", "drum", "barrel"], []),
    ("⛽", ["fuel", "pump", "gas"], []),
    ("🛞", ["wheel", "tire", "car"], []),
    ("🚨", ["police", "light", "emergency"], []),
    ("🚥", ["horizontal", "traffic", "light"], []),
    ("🚦", ["vertical", "traffic", "light"], []),
    ("🛑", ["stop", "sign", "octagon"], []),
    ("🚧", ["construction", "sign", "warning"], []),

    # Transportation - Water
    ("⚓", ["anchor", "ship", "boat"], []),
    ("🛟", ["ring", "buoy", "life", "saver"], []),
    ("⛵", ["sailboat", "boat", "sailing"], []),
    ("🛶", ["canoe", "boat", "kayak"], []),
    ("🚤", ["speedboat", "boat", "motorboat"], []),
    ("🛳️", ["passenger", "ship", "cruise"], []),
    ("⛴️", ["ferry", "boat", "ship"], []),
    ("🛥️", ["motor", "boat", "speedboat"], []),
    ("🚢", ["ship", "boat", "vessel"], []),

    # Transportation - Air
    ("✈️", ["airplane", "plane", "flight"], []),
    ("🛩️", ["small", "airplane", "plane"], []),
    ("🛫", ["airplane", "departure", "takeoff"], []),
    ("🛬", ["airplane", "arrival", "landing"], []),
    ("🪂", ["parachute", "skydive", "parasail"], []),
    ("💺", ["seat", "chair", "airplane"], []),
    ("🚁", ["helicopter", "chopper", "vehicle"], []),
    ("🚟", ["suspension", "railway", "train"], []),
    ("🚠", ["mountain", "cableway", "gondola"], []),
    ("🚡", ["aerial", "tramway", "cable"], []),
    ("🛰️", ["satellite", "space", "orbit"], []),
    ("🚀", ["rocket", "space", "launch"], []),
    ("🛸", ["flying", "saucer", "ufo"], []),

    # Hotel & Time
    ("🛎️", ["bellhop", "bell", "service"], []),
    ("🧳", ["luggage", "suitcase", "baggage"], []),
    ("⌛", ["hourglass", "done", "time"], []),
    ("⏳", ["hourglass", "not", "done"], []),
    ("⌚", ["watch", "time", "clock"], []),
    ("⏰", ["alarm", "clock", "wake"], []),
    ("⏱️", ["stopwatch", "time", "timer"], []),
    ("⏲️", ["timer", "clock", "cooking"], []),
    ("🕰️", ["mantelpiece", "clock", "time"], []),
    ("🕛", ["twelve", "oclock", "00"], []),
    ("🕧", ["twelve", "thirty", "1230"], []),
    ("🕐", ["one", "oclock", "100"], []),
    ("🕜", ["one", "thirty", "130"], []),
    ("🕑", ["two", "oclock", "200"], []),
    ("🕝", ["two", "thirty", "230"], []),
    ("🕒", ["three", "oclock", "300"], []),
    ("🕞", ["three", "thirty", "330"], []),
    ("🕓", ["four", "oclock", "400"], []),
    ("🕟", ["four", "thirty", "430"], []),
    ("🕔", ["five", "oclock", "500"], []),
    ("🕠", ["five", "thirty", "530"], []),
    ("🕕", ["six", "oclock", "600"], []),
    ("🕡", ["six", "thirty", "630"], []),
    ("🕖", ["seven", "oclock", "700"], []),
    ("🕢", ["seven", "thirty", "730"], []),
    ("🕗", ["eight", "oclock", "800"], []),
    ("🕣", ["eight", "thirty", "830"], []),
    ("🕘", ["nine", "oclock", "900"], []),
    ("🕤", ["nine", "thirty", "930"], []),
    ("🕙", ["ten", "oclock", "1000"], []),
    ("🕥", ["ten", "thirty", "1030"], []),
    ("🕚", ["eleven", "oclock", "1100"], []),
    ("🕦", ["eleven", "thirty", "1130"], []),

    # Sky & Weather
    ("🌑", ["new", "moon", "dark"], []),
    ("🌒", ["waxing", "crescent", "moon"], []),
    ("🌓", ["first", "quarter", "moon"], []),
    ("🌔", ["waxing", "gibbous", "moon"], []),
    ("🌕", ["full", "moon", "bright"], []),
    ("🌖", ["waning", "gibbous", "moon"], []),
    ("🌗", ["last", "quarter", "moon"], []),
    ("🌘", ["waning", "crescent", "moon"], []),
    ("🌙", ["crescent", "moon", "night"], []),
    ("🌚", ["new", "moon", "face"], []),
    ("🌛", ["first", "quarter", "moon", "face"], []),
    ("🌜", ["last", "quarter", "moon", "face"], []),
    ("🌡️", ["thermometer", "temperature", "weather"], []),
    ("☀️", ["sun", "sunny", "bright"], []),
    ("🌝", ["full", "moon", "face"], []),
    ("🌞", ["sun", "with", "face"], []),
    ("🪐", ["saturn", "ringed", "planet"], []),
    ("⭐", ["star", "excellent", "favorite"], []),
    ("🌟", ["glowing", "star", "shining"], []),
    ("🌠", ["shooting", "star", "wish"], []),
    ("🌌", ["milky", "way", "galaxy"], []),
    ("☁️", ["cloud", "cloudy", "weather"], []),
    ("⛅", ["sun", "behind", "cloud"], []),
    ("⛈️", ["cloud", "lightning", "rain"], []),
    ("🌤️", ["sun", "small", "cloud"], []),
    ("🌥️", ["sun", "large", "cloud"], []),
    ("🌦️", ["sun", "behind", "rain", "cloud"], []),
    ("🌧️", ["cloud", "with", "rain"], []),
    ("🌨️", ["cloud", "with", "snow"], []),
    ("🌩️", ["cloud", "with", "lightning"], []),
    ("🌪️", ["tornado", "cyclone", "twister"], []),
    ("🌫️", ["fog", "cloudy", "mist"], []),
    ("🌬️", ["wind", "face", "blowing"], []),
    ("🌀", ["cyclone", "hurricane", "typhoon"], []),
    ("🌈", ["rainbow", "colors", "weather"], []),
    ("🌂", ["closed", "umbrella", "rain"], []),
    ("☂️", ["umbrella", "rain", "protection"], []),
    ("☔", ["umbrella", "with", "rain"], []),
    ("⛱️", ["umbrella", "on", "ground"], []),
    ("⚡", ["lightning", "bolt", "electric"], []),
    ("❄️", ["snowflake", "snow", "cold"], []),
    ("☃️", ["snowman", "snow", "winter"], []),
    ("⛄", ["snowman", "without", "snow"], []),
    ("☄️", ["comet", "space", "meteor"], []),
    ("🔥", ["fire", "hot", "lit"], []),
    ("💧", ["droplet", "water", "drop"], []),
    ("🌊", ["water", "wave", "ocean"], []),
]

# Activities
ACTIVITIES = [
    # Sports
    ("🎃", ["jack", "o", "lantern", "halloween"], []),
    ("🎄", ["christmas", "tree", "celebration"], []),
    ("🎆", ["fireworks", "celebration", "festival"], []),
    ("🎇", ["sparkler", "fireworks", "celebration"], []),
    ("🧨", ["firecracker", "dynamite", "explosive"], []),
    ("✨", ["sparkles", "shine", "glitter"], []),
    ("🎈", ["balloon", "party", "celebration"], []),
    ("🎉", ["party", "popper", "celebrate"], []),
    ("🎊", ["confetti", "ball", "party"], []),
    ("🎋", ["tanabata", "tree", "wish"], []),
    ("🎍", ["pine", "decoration", "bamboo"], []),
    ("🎎", ["dolls", "japanese", "festival"], []),
    ("🎏", ["carp", "streamer", "koinobori"], []),
    ("🎐", ["wind", "chime", "bell"], []),
    ("🎑", ["moon", "viewing", "ceremony"], []),
    ("🧧", ["red", "envelope", "gift"], []),
    ("🎀", ["ribbon", "bow", "decoration"], []),
    ("🎁", ["gift", "present", "wrapped"], []),
    ("🎗️", ["reminder", "ribbon", "awareness"], []),
    ("🎟️", ["admission", "tickets", "event"], []),
    ("🎫", ["ticket", "admission", "event"], []),

    # Awards
    ("🎖️", ["military", "medal", "award"], []),
    ("🏆", ["trophy", "win", "award"], []),
    ("🏅", ["sports", "medal", "first"], []),
    ("🥇", ["gold", "medal", "first"], []),
    ("🥈", ["silver", "medal", "second"], []),
    ("🥉", ["bronze", "medal", "third"], []),

    # Sports
    ("⚽", ["soccer", "ball", "football"], []),
    ("⚾", ["baseball", "ball", "sport"], []),
    ("🥎", ["softball", "ball", "sport"], []),
    ("🏀", ["basketball", "ball", "sport"], []),
    ("🏐", ["volleyball", "ball", "sport"], []),
    ("🏈", ["american", "football", "ball"], []),
    ("🏉", ["rugby", "football", "ball"], []),
    ("🎾", ["tennis", "ball", "sport"], []),
    ("🥏", ["flying", "disc", "frisbee"], []),
    ("🎳", ["bowling", "ball", "sport"], []),
    ("🏏", ["cricket", "game", "bat"], []),
    ("🏑", ["field", "hockey", "stick"], []),
    ("🏒", ["ice", "hockey", "stick"], []),
    ("🥍", ["lacrosse", "stick", "ball"], []),
    ("🏓", ["ping", "pong", "table", "tennis"], []),
    ("🏸", ["badminton", "racquet", "shuttlecock"], []),
    ("🥊", ["boxing", "glove", "sport"], []),
    ("🥋", ["martial", "arts", "uniform"], []),
    ("🥅", ["goal", "net", "sport"], []),
    ("⛳", ["flag", "hole", "golf"], []),
    ("⛸️", ["ice", "skate", "skating"], []),
    ("🎣", ["fishing", "pole", "fish"], []),
    ("🤿", ["diving", "mask", "scuba"], []),
    ("🎽", ["running", "shirt", "athletics"], []),
    ("🎿", ["skis", "skiing", "sport"], []),
    ("🛷", ["sled", "sledding", "snow"], []),
    ("🥌", ["curling", "stone", "sport"], []),

    # Games & Hobbies
    ("🎯", ["direct", "hit", "target", "bullseye"], []),
    ("🪀", ["yo-yo", "toy", "game"], []),
    ("🪁", ["kite", "flying", "toy"], []),
    ("🎱", ["pool", "8", "ball", "billiards"], []),
    ("🔮", ["crystal", "ball", "fortune"], []),
    ("🪄", ["magic", "wand", "wizard"], []),
    ("🧿", ["nazar", "amulet", "evil", "eye"], []),
    ("🪬", ["hamsa", "hand", "fatima"], []),
    ("🎮", ["video", "game", "controller"], []),
    ("🕹️", ["joystick", "game", "arcade"], []),
    ("🎰", ["slot", "machine", "gambling"], []),
    ("🎲", ["dice", "game", "random"], []),
    ("🧩", ["puzzle", "piece", "jigsaw"], []),
    ("🧸", ["teddy", "bear", "toy"], []),
    ("🪅", ["pinata", "party", "candy"], []),
    ("🪩", ["mirror", "ball", "disco"], []),
    ("🪆", ["nesting", "dolls", "matryoshka"], []),
    ("♠️", ["spade", "suit", "cards"], []),
    ("♥️", ["heart", "suit", "cards"], []),
    ("♦️", ["diamond", "suit", "cards"], []),
    ("♣️", ["club", "suit", "cards"], []),
    ("♟️", ["chess", "pawn", "game"], []),
    ("🃏", ["joker", "card", "wild"], []),
    ("🀄", ["mahjong", "red", "dragon"], []),
    ("🎴", ["flower", "playing", "cards"], []),

    # Arts & Crafts
    ("🎭", ["performing", "arts", "theater", "mask"], []),
    ("🖼️", ["framed", "picture", "painting"], []),
    ("🎨", ["artist", "palette", "paint"], []),
    ("🧵", ["thread", "spool", "sewing"], []),
    ("🪡", ["sewing", "needle", "stitching"], []),
    ("🧶", ["yarn", "ball", "knitting"], []),
    ("🪢", ["knot", "rope", "tie"], []),
]

# Objects
OBJECTS = [
    # Clothing
    ("👓", ["glasses", "eyeglasses", "spectacles"], []),
    ("🕶️", ["sunglasses", "dark", "glasses"], []),
    ("🥽", ["goggles", "swimming", "diving"], []),
    ("🥼", ["lab", "coat", "scientist"], []),
    ("🦺", ["safety", "vest", "construction"], []),
    ("👔", ["necktie", "tie", "formal"], []),
    ("👕", ["t-shirt", "shirt", "tshirt"], []),
    ("👖", ["jeans", "pants", "trousers"], []),
    ("🧣", ["scarf", "neck", "warm"], []),
    ("🧤", ["gloves", "hands", "warm"], []),
    ("🧥", ["coat", "jacket", "outerwear"], []),
    ("🧦", ["socks", "feet", "footwear"], []),
    ("👗", ["dress", "clothing", "woman"], []),
    ("👘", ["kimono", "japanese", "clothing"], []),
    ("🥻", ["sari", "clothing", "dress"], []),
    ("🩱", ["one", "piece", "swimsuit"], []),
    ("🩲", ["briefs", "underwear", "shorts"], []),
    ("🩳", ["shorts", "pants", "short"], []),
    ("👙", ["bikini", "swimsuit", "beach"], []),
    ("👚", ["blouse", "shirt", "woman"], []),
    ("🪭", ["folding", "hand", "fan"], []),
    ("👛", ["purse", "wallet", "money"], []),
    ("👜", ["handbag", "purse", "bag"], []),
    ("👝", ["clutch", "bag", "purse"], []),
    ("🛍️", ["shopping", "bags", "purchase"], []),
    ("🎒", ["backpack", "bag", "school"], []),
    ("🩴", ["thong", "sandal", "flip", "flop"], []),
    ("👞", ["mans", "shoe", "dress"], []),
    ("👟", ["running", "shoe", "sneaker"], []),
    ("🥾", ["hiking", "boot", "outdoor"], []),
    ("🥿", ["flat", "shoe", "ballet"], []),
    ("👠", ["high", "heeled", "shoe"], []),
    ("👡", ["sandal", "woman", "shoe"], []),
    ("🩰", ["ballet", "shoes", "dance"], []),
    ("👢", ["boot", "womans", "shoe"], []),
    ("🪮", ["hair", "pick", "comb"], []),
    ("👑", ["crown", "king", "queen"], []),
    ("👒", ["hat", "womans", "sun"], []),
    ("🎩", ["top", "hat", "formal"], []),
    ("🎓", ["graduation", "cap", "mortarboard"], []),
    ("🧢", ["billed", "cap", "baseball"], []),
    ("🪖", ["military", "helmet", "army"], []),
    ("⛑️", ["rescue", "workers", "helmet"], []),
    ("📿", ["prayer", "beads", "rosary"], []),
    ("💄", ["lipstick", "makeup", "cosmetics"], []),
    ("💍", ["ring", "diamond", "engagement"], []),
    ("💎", ["gem", "stone", "diamond"], []),

    # Sound
    ("🔇", ["muted", "speaker", "silent"], []),
    ("🔈", ["speaker", "low", "volume"], []),
    ("🔉", ["speaker", "medium", "volume"], []),
    ("🔊", ["speaker", "high", "volume"], []),
    ("📢", ["loudspeaker", "announcement", "public"], []),
    ("📣", ["megaphone", "cheering", "announcement"], []),
    ("📯", ["postal", "horn", "announcement"], []),
    ("🔔", ["bell", "notification", "alert"], []),
    ("🔕", ["bell", "slash", "mute"], []),

    # Music
    ("🎼", ["musical", "score", "treble", "clef"], []),
    ("🎵", ["musical", "note", "music"], []),
    ("🎶", ["musical", "notes", "music"], []),
    ("🎙️", ["studio", "microphone", "podcast"], []),
    ("🎚️", ["level", "slider", "control"], []),
    ("🎛️", ["control", "knobs", "dials"], []),
    ("🎤", ["microphone", "sing", "karaoke"], []),
    ("🎧", ["headphone", "music", "audio"], []),
    ("📻", ["radio", "broadcast", "music"], []),
    ("🎷", ["saxophone", "instrument", "music"], []),
    ("🪗", ["accordion", "instrument", "music"], []),
    ("🎸", ["guitar", "instrument", "music"], []),
    ("🎹", ["musical", "keyboard", "piano"], []),
    ("🎺", ["trumpet", "instrument", "music"], []),
    ("🎻", ["violin", "instrument", "music"], []),
    ("🪕", ["banjo", "instrument", "music"], []),
    ("🥁", ["drum", "instrument", "music"], []),
    ("🪘", ["long", "drum", "instrument"], []),
    ("🪇", ["maracas", "instrument", "rattle"], []),
    ("🪈", ["flute", "instrument", "music"], []),

    # Phone & Computer
    ("📱", ["mobile", "phone", "cell"], []),
    ("📲", ["mobile", "arrow", "call"], []),
    ("☎️", ["telephone", "phone", "call"], []),
    ("📞", ["telephone", "receiver", "phone"], []),
    ("📟", ["pager", "beeper", "device"], []),
    ("📠", ["fax", "machine", "document"], []),

    # Computer
    ("🔋", ["battery", "power", "charge"], []),
    ("🪫", ["battery", "low", "empty"], []),
    ("🔌", ["electric", "plug", "power"], []),
    ("💻", ["laptop", "computer", "pc"], []),
    ("🖥️", ["desktop", "computer", "pc"], []),
    ("🖨️", ["printer", "print", "document"], []),
    ("⌨️", ["keyboard", "computer", "typing"], []),
    ("🖱️", ["computer", "mouse", "click"], []),
    ("🖲️", ["trackball", "mouse", "pointing"], []),
    ("💽", ["computer", "disk", "minidisc"], []),
    ("💾", ["floppy", "disk", "save"], []),
    ("💿", ["optical", "disk", "cd"], []),
    ("📀", ["dvd", "disk", "optical"], []),
    ("🧮", ["abacus", "calculation", "counting"], []),

    # Video
    ("🎥", ["movie", "camera", "film"], []),
    ("🎞️", ["film", "frames", "movie"], []),
    ("📽️", ["film", "projector", "movie"], []),
    ("🎬", ["clapper", "board", "movie"], []),
    ("📺", ["television", "tv", "video"], []),
    ("📷", ["camera", "photo", "picture"], []),
    ("📸", ["camera", "flash", "photo"], []),
    ("📹", ["video", "camera", "recording"], []),
    ("📼", ["videocassette", "vhs", "tape"], []),

    # Light & Optics
    ("🔍", ["magnifying", "glass", "left", "search"], []),
    ("🔎", ["magnifying", "glass", "right", "search"], []),
    ("🕯️", ["candle", "light", "flame"], []),
    ("💡", ["light", "bulb", "idea"], []),
    ("🔦", ["flashlight", "torch", "light"], []),
    ("🏮", ["red", "paper", "lantern"], []),
    ("🪔", ["diya", "lamp", "oil"], []),

    # Books & Paper
    ("📔", ["notebook", "decorative", "cover"], []),
    ("📕", ["closed", "book", "red"], []),
    ("📖", ["open", "book", "read"], []),
    ("📗", ["green", "book", "closed"], []),
    ("📘", ["blue", "book", "closed"], []),
    ("📙", ["orange", "book", "closed"], []),
    ("📚", ["books", "library", "stack"], []),
    ("📓", ["notebook", "writing"], []),
    ("📒", ["ledger", "notebook", "writing"], []),
    ("📃", ["page", "curl", "document"], []),
    ("📜", ["scroll", "paper", "ancient"], []),
    ("📄", ["page", "facing", "up", "document"], []),
    ("📰", ["newspaper", "news", "press"], []),
    ("🗞️", ["rolled", "newspaper", "news"], []),
    ("📑", ["bookmark", "tabs", "mark"], []),
    ("🔖", ["bookmark", "mark", "tag"], []),
    ("🏷️", ["label", "tag", "price"], []),

    # Money
    ("💰", ["money", "bag", "dollar"], []),
    ("🪙", ["coin", "money", "currency"], []),
    ("💴", ["yen", "banknote", "japan"], []),
    ("💵", ["dollar", "banknote", "money"], []),
    ("💶", ["euro", "banknote", "money"], []),
    ("💷", ["pound", "banknote", "britain"], []),
    ("💸", ["money", "wings", "fly"], []),
    ("💳", ["credit", "card", "payment"], []),
    ("🧾", ["receipt", "proof", "payment"], []),
    ("💹", ["chart", "increasing", "yen"], []),

    # Mail
    ("✉️", ["envelope", "mail", "letter"], []),
    ("📧", ["e-mail", "email", "message"], []),
    ("📨", ["incoming", "envelope", "mail"], []),
    ("📩", ["envelope", "arrow", "mail"], []),
    ("📤", ["outbox", "tray", "send"], []),
    ("📥", ["inbox", "tray", "receive"], []),
    ("📦", ["package", "box", "parcel"], []),
    ("📫", ["closed", "mailbox", "raised"], []),
    ("📪", ["closed", "mailbox", "lowered"], []),
    ("📬", ["open", "mailbox", "raised"], []),
    ("📭", ["open", "mailbox", "lowered"], []),
    ("📮", ["postbox", "mailbox", "mail"], []),
    ("🗳️", ["ballot", "box", "vote"], []),

    # Writing
    ("✏️", ["pencil", "write", "draw"], []),
    ("✒️", ["black", "nib", "pen"], []),
    ("🖋️", ["fountain", "pen", "write"], []),
    ("🖊️", ["pen", "ballpoint", "write"], []),
    ("🖌️", ["paintbrush", "brush", "painting"], []),
    ("🖍️", ["crayon", "drawing", "color"], []),
    ("📝", ["memo", "note", "pencil"], []),

    # Office
    ("💼", ["briefcase", "business", "work"], []),
    ("📁", ["file", "folder", "directory"], []),
    ("📂", ["open", "file", "folder"], []),
    ("🗂️", ["card", "index", "dividers"], []),
    ("📅", ["calendar", "date", "schedule"], []),
    ("📆", ["tear-off", "calendar", "date"], []),
    ("🗒️", ["spiral", "notepad", "note"], []),
    ("🗓️", ["spiral", "calendar", "date"], []),
    ("📇", ["card", "index", "rolodex"], []),
    ("📈", ["chart", "increasing", "growth"], []),
    ("📉", ["chart", "decreasing", "down"], []),
    ("📊", ["bar", "chart", "graph"], []),
    ("📋", ["clipboard", "copy", "paste"], []),
    ("📌", ["pushpin", "pin", "mark"], []),
    ("📍", ["round", "pushpin", "location"], []),
    ("📎", ["paperclip", "attachment", "clip"], []),
    ("🖇️", ["linked", "paperclips", "attach"], []),
    ("📏", ["straight", "ruler", "measure"], []),
    ("📐", ["triangular", "ruler", "set"], []),
    ("✂️", ["scissors", "cut", "tool"], []),
    ("🗃️", ["card", "file", "box"], []),
    ("🗄️", ["file", "cabinet", "storage"], []),
    ("🗑️", ["wastebasket", "trash", "delete"], []),

    # Lock & Key
    ("🔒", ["locked", "secure", "private"], []),
    ("🔓", ["unlocked", "open", "unsecure"], []),
    ("🔏", ["locked", "pen", "ink"], []),
    ("🔐", ["locked", "key", "secure"], []),
    ("🔑", ["key", "unlock", "password"], []),
    ("🗝️", ["old", "key", "unlock"], []),

    # Tools
    ("🔨", ["hammer", "tool", "fix"], []),
    ("🪓", ["axe", "tool", "chop"], []),
    ("⛏️", ["pick", "tool", "mining"], []),
    ("⚒️", ["hammer", "pick", "tools"], []),
    ("🛠️", ["hammer", "wrench", "tools"], []),
    ("🗡️", ["dagger", "knife", "weapon"], []),
    ("⚔️", ["crossed", "swords", "weapons"], []),
    ("🔫", ["water", "pistol", "gun"], []),
    ("🪃", ["boomerang", "weapon", "australia"], []),
    ("🏹", ["bow", "arrow", "archery"], []),
    ("🛡️", ["shield", "protection", "defense"], []),
    ("🪚", ["carpentry", "saw", "tool"], []),
    ("🔧", ["wrench", "tool", "fix"], []),
    ("🪛", ["screwdriver", "tool", "fix"], []),
    ("🔩", ["nut", "bolt", "fastener"], []),
    ("⚙️", ["gear", "settings", "cog"], []),
    ("🗜️", ["clamp", "compress", "tool"], []),
    ("⚖️", ["balance", "scale", "justice"], []),
    ("🦯", ["probing", "cane", "blind"], []),
    ("🔗", ["link", "chain", "connection"], []),
    ("⛓️‍💥", ["broken", "chain", "shackle"], []),
    ("⛓️", ["chains", "link", "metal"], []),
    ("🪝", ["hook", "catch", "hang"], []),
    ("🧰", ["toolbox", "tools", "mechanic"], []),
    ("🧲", ["magnet", "attraction", "horseshoe"], []),
    ("🪜", ["ladder", "climb", "step"], []),

    # Science
    ("⚗️", ["alembic", "chemistry", "distilling"], []),
    ("🧪", ["test", "tube", "chemistry"], []),
    ("🧫", ["petri", "dish", "bacteria"], []),
    ("🧬", ["dna", "genetics", "gene"], []),
    ("🔬", ["microscope", "science", "lab"], []),
    ("🔭", ["telescope", "astronomy", "space"], []),
    ("📡", ["satellite", "antenna", "signal"], []),

    # Medical
    ("💉", ["syringe", "needle", "vaccine"], []),
    ("🩸", ["drop", "blood", "donation"], []),
    ("💊", ["pill", "medicine", "drug"], []),
    ("🩹", ["adhesive", "bandage", "plaster"], []),
    ("🩼", ["crutch", "disability", "injured"], []),
    ("🩺", ["stethoscope", "doctor", "heartbeat"], []),
    ("🩻", ["x-ray", "bones", "medical"], []),

    # Household
    ("🚪", ["door", "entrance", "exit"], []),
    ("🛗", ["elevator", "lift", "floors"], []),
    ("🪞", ["mirror", "reflection", "looking"], []),
    ("🪟", ["window", "view", "frame"], []),
    ("🛏️", ["bed", "sleep", "hotel"], []),
    ("🛋️", ["couch", "lamp", "sofa"], []),
    ("🪑", ["chair", "sit", "seat"], []),
    ("🚽", ["toilet", "bathroom", "loo"], []),
    ("🪠", ["plunger", "toilet", "tool"], []),
    ("🚿", ["shower", "bath", "clean"], []),
    ("🛁", ["bathtub", "bath", "clean"], []),
    ("🪤", ["mouse", "trap", "snare"], []),
    ("🪒", ["razor", "shave", "blade"], []),
    ("🧴", ["lotion", "bottle", "moisturizer"], []),
    ("🧷", ["safety", "pin", "diaper"], []),
    ("🧹", ["broom", "cleaning", "sweep"], []),
    ("🧺", ["basket", "laundry", "picnic"], []),
    ("🧻", ["roll", "paper", "toilet"], []),
    ("🪣", ["bucket", "pail", "water"], []),
    ("🧼", ["soap", "bar", "clean"], []),
    ("🫧", ["bubbles", "soap", "clean"], []),
    ("🪥", ["toothbrush", "dental", "hygiene"], []),
    ("🧽", ["sponge", "cleaning", "absorbing"], []),
    ("🧯", ["fire", "extinguisher", "quench"], []),
    ("🛒", ["shopping", "cart", "trolley"], []),

    # Smoking
    ("🚬", ["cigarette", "smoking", "smoke"], []),
    ("⚰️", ["coffin", "funeral", "death"], []),
    ("🪦", ["headstone", "grave", "rip"], []),
    ("⚱️", ["urn", "funeral", "ashes"], []),
    ("🗿", ["moai", "easter", "island"], []),
    ("🪧", ["placard", "sign", "protest"], []),
    ("🪪", ["identification", "card", "id"], []),
]

# Symbols
SYMBOLS = [
    # Transport signs
    ("🏧", ["atm", "sign", "cash"], []),
    ("🚮", ["litter", "bin", "trash"], []),
    ("🚰", ["potable", "water", "drinking"], []),
    ("♿", ["wheelchair", "symbol", "accessible"], []),
    ("🚹", ["mens", "room", "restroom"], []),
    ("🚺", ["womens", "room", "restroom"], []),
    ("🚻", ["restroom", "bathroom", "toilet"], []),
    ("🚼", ["baby", "symbol", "changing"], []),
    ("🚾", ["water", "closet", "wc"], []),
    ("🛂", ["passport", "control", "border"], []),
    ("🛃", ["customs", "border", "baggage"], []),
    ("🛄", ["baggage", "claim", "luggage"], []),
    ("🛅", ["left", "luggage", "locker"], []),

    # Warning
    ("⚠️", ["warning", "caution", "alert"], []),
    ("🚸", ["children", "crossing", "school"], []),
    ("⛔", ["no", "entry", "forbidden"], []),
    ("🚫", ["prohibited", "forbidden", "not"], []),
    ("🚳", ["no", "bicycles", "bikes"], []),
    ("🚭", ["no", "smoking", "cigarette"], []),
    ("🚯", ["no", "littering", "trash"], []),
    ("🚱", ["non-potable", "water", "drink"], []),
    ("🚷", ["no", "pedestrians", "walking"], []),
    ("📵", ["no", "mobile", "phones"], []),
    ("🔞", ["no", "one", "under", "18"], []),
    ("☢️", ["radioactive", "nuclear", "danger"], []),
    ("☣️", ["biohazard", "danger", "toxic"], []),

    # Arrow
    ("⬆️", ["up", "arrow", "north"], []),
    ("↗️", ["up-right", "arrow", "northeast"], []),
    ("➡️", ["right", "arrow", "east"], []),
    ("↘️", ["down-right", "arrow", "southeast"], []),
    ("⬇️", ["down", "arrow", "south"], []),
    ("↙️", ["down-left", "arrow", "southwest"], []),
    ("⬅️", ["left", "arrow", "west"], []),
    ("↖️", ["up-left", "arrow", "northwest"], []),
    ("↕️", ["up-down", "arrow", "vertical"], []),
    ("↔️", ["left-right", "arrow", "horizontal"], []),
    ("↩️", ["right", "arrow", "curving", "left"], []),
    ("↪️", ["left", "arrow", "curving", "right"], []),
    ("⤴️", ["right", "arrow", "curving", "up"], []),
    ("⤵️", ["right", "arrow", "curving", "down"], []),
    ("🔃", ["clockwise", "arrows", "reload"], []),
    ("🔄", ["counterclockwise", "arrows", "reload"], []),
    ("🔙", ["back", "arrow", "return"], []),
    ("🔚", ["end", "arrow", "finish"], []),
    ("🔛", ["on", "arrow", "mark"], []),
    ("🔜", ["soon", "arrow", "mark"], []),
    ("🔝", ["top", "arrow", "mark"], []),

    # Religious
    ("🛐", ["place", "worship", "religion"], []),
    ("⚛️", ["atom", "symbol", "science"], []),
    ("🕉️", ["om", "hindu", "symbol"], []),
    ("✡️", ["star", "david", "jewish"], []),
    ("☸️", ["wheel", "dharma", "buddhist"], []),
    ("☯️", ["yin", "yang", "balance"], []),
    ("✝️", ["latin", "cross", "christian"], []),
    ("☦️", ["orthodox", "cross", "christian"], []),
    ("☪️", ["star", "crescent", "islam"], []),
    ("☮️", ["peace", "symbol", "hippie"], []),
    ("🕎", ["menorah", "candelabrum", "jewish"], []),
    ("🔯", ["dotted", "six-pointed", "star"], []),
    ("🪯", ["khanda", "sikh", "symbol"], []),

    # Zodiac
    ("♈", ["aries", "zodiac", "ram"], []),
    ("♉", ["taurus", "zodiac", "bull"], []),
    ("♊", ["gemini", "zodiac", "twins"], []),
    ("♋", ["cancer", "zodiac", "crab"], []),
    ("♌", ["leo", "zodiac", "lion"], []),
    ("♍", ["virgo", "zodiac", "maiden"], []),
    ("♎", ["libra", "zodiac", "scales"], []),
    ("♏", ["scorpio", "zodiac", "scorpion"], []),
    ("♐", ["sagittarius", "zodiac", "archer"], []),
    ("♑", ["capricorn", "zodiac", "goat"], []),
    ("♒", ["aquarius", "zodiac", "water"], []),
    ("♓", ["pisces", "zodiac", "fish"], []),
    ("⛎", ["ophiuchus", "zodiac", "serpent"], []),

    # AV symbols
    ("🔀", ["shuffle", "tracks", "random"], []),
    ("🔁", ["repeat", "button", "loop"], []),
    ("🔂", ["repeat", "single", "button"], []),
    ("▶️", ["play", "button", "start"], []),
    ("⏩", ["fast", "forward", "button"], []),
    ("⏭️", ["next", "track", "button"], []),
    ("⏯️", ["play", "pause", "button"], []),
    ("◀️", ["reverse", "button", "back"], []),
    ("⏪", ["fast", "reverse", "button"], []),
    ("⏮️", ["last", "track", "button"], []),
    ("🔼", ["upwards", "button", "triangle"], []),
    ("⏫", ["fast", "up", "button"], []),
    ("🔽", ["downwards", "button", "triangle"], []),
    ("⏬", ["fast", "down", "button"], []),
    ("⏸️", ["pause", "button", "stop"], []),
    ("⏹️", ["stop", "button", "square"], []),
    ("⏺️", ["record", "button", "circle"], []),
    ("⏏️", ["eject", "button", "symbol"], []),
    ("🎦", ["cinema", "movie", "film"], []),
    ("🔅", ["dim", "button", "low"], []),
    ("🔆", ["bright", "button", "high"], []),
    ("📶", ["antenna", "bars", "signal"], []),
    ("🛜", ["wireless", "wifi", "signal"], []),
    ("📳", ["vibration", "mode", "silent"], []),
    ("📴", ["mobile", "phone", "off"], []),

    # Gender & Family
    ("♀️", ["female", "sign", "woman"], []),
    ("♂️", ["male", "sign", "man"], []),
    ("⚧️", ["transgender", "symbol", "trans"], []),

    # Math
    ("✖️", ["multiply", "multiplication", "times"], []),
    ("➕", ["plus", "add", "addition"], []),
    ("➖", ["minus", "subtract", "subtraction"], []),
    ("➗", ["divide", "division", "sign"], []),
    ("🟰", ["heavy", "equals", "sign"], []),
    ("♾️", ["infinity", "forever", "unlimited"], []),

    # Punctuation
    ("‼️", ["double", "exclamation", "mark"], []),
    ("⁉️", ["exclamation", "question", "mark"], []),
    ("❓", ["question", "mark", "red"], []),
    ("❔", ["question", "mark", "white"], []),
    ("❕", ["exclamation", "mark", "white"], []),
    ("❗", ["exclamation", "mark", "red"], []),
    ("〰️", ["wavy", "dash", "symbol"], []),

    # Currency
    ("💱", ["currency", "exchange", "money"], []),
    ("💲", ["heavy", "dollar", "sign"], []),

    # Other symbols
    ("⚕️", ["medical", "symbol", "staff"], []),
    ("♻️", ["recycling", "symbol", "green"], []),
    ("⚜️", ["fleur-de-lis", "symbol", "scout"], []),
    ("🔱", ["trident", "emblem", "weapon"], []),
    ("📛", ["name", "badge", "tag"], []),
    ("🔰", ["japanese", "symbol", "beginner"], []),
    ("⭕", ["hollow", "red", "circle"], []),
    ("✅", ["check", "mark", "button"], []),
    ("☑️", ["check", "box", "mark"], []),
    ("✔️", ["check", "mark", "tick"], []),
    ("❌", ["cross", "mark", "x"], []),
    ("❎", ["cross", "mark", "button"], []),
    ("➰", ["curly", "loop", "symbol"], []),
    ("➿", ["double", "curly", "loop"], []),
    ("〽️", ["part", "alternation", "mark"], []),
    ("✳️", ["eight", "spoked", "asterisk"], []),
    ("✴️", ["eight", "pointed", "star"], []),
    ("❇️", ["sparkle", "decoration", "star"], []),
    ("©️", ["copyright", "symbol", "mark"], []),
    ("®️", ["registered", "trademark", "symbol"], []),
    ("™️", ["trade", "mark", "symbol"], []),

    # Keycaps
    ("#️⃣", ["keycap", "hash", "number"], []),
    ("*️⃣", ["keycap", "asterisk", "star"], []),
    ("0️⃣", ["keycap", "0", "zero"], []),
    ("1️⃣", ["keycap", "1", "one"], []),
    ("2️⃣", ["keycap", "2", "two"], []),
    ("3️⃣", ["keycap", "3", "three"], []),
    ("4️⃣", ["keycap", "4", "four"], []),
    ("5️⃣", ["keycap", "5", "five"], []),
    ("6️⃣", ["keycap", "6", "six"], []),
    ("7️⃣", ["keycap", "7", "seven"], []),
    ("8️⃣", ["keycap", "8", "eight"], []),
    ("9️⃣", ["keycap", "9", "nine"], []),
    ("🔟", ["keycap", "10", "ten"], []),

    # Alphabet
    ("🔠", ["input", "latin", "uppercase"], []),
    ("🔡", ["input", "latin", "lowercase"], []),
    ("🔢", ["input", "numbers", "1234"], []),
    ("🔣", ["input", "symbols", "special"], []),
    ("🔤", ["input", "latin", "letters"], []),
    ("🅰️", ["button", "blood", "type", "a"], []),
    ("🆎", ["button", "blood", "type", "ab"], []),
    ("🅱️", ["button", "blood", "type", "b"], []),
    ("🆑", ["cl", "button", "clear"], []),
    ("🆒", ["cool", "button", "awesome"], []),
    ("🆓", ["free", "button", "gratis"], []),
    ("ℹ️", ["information", "info", "i"], []),
    ("🆔", ["id", "button", "identity"], []),
    ("Ⓜ️", ["circled", "m", "metro"], []),
    ("🆕", ["new", "button", "fresh"], []),
    ("🆖", ["ng", "button", "no", "good"], []),
    ("🅾️", ["button", "blood", "type", "o"], []),
    ("🆗", ["ok", "button", "okay"], []),
    ("🅿️", ["parking", "button", "p"], []),
    ("🆘", ["sos", "button", "help"], []),
    ("🆙", ["up", "button", "mark"], []),
    ("🆚", ["vs", "button", "versus"], []),
    ("🈁", ["japanese", "here", "button"], []),
    ("🈂️", ["japanese", "service", "charge"], []),
    ("🈷️", ["japanese", "monthly", "amount"], []),
    ("🈶", ["japanese", "not", "free"], []),
    ("🈯", ["japanese", "reserved", "button"], []),
    ("🉐", ["japanese", "bargain", "button"], []),
    ("🈹", ["japanese", "discount", "button"], []),
    ("🈚", ["japanese", "free", "charge"], []),
    ("🈲", ["japanese", "prohibited", "button"], []),
    ("🉑", ["japanese", "acceptable", "button"], []),
    ("🈸", ["japanese", "application", "button"], []),
    ("🈴", ["japanese", "passing", "grade"], []),
    ("🈳", ["japanese", "vacancy", "button"], []),
    ("㊗️", ["japanese", "congratulations", "button"], []),
    ("㊙️", ["japanese", "secret", "button"], []),
    ("🈺", ["japanese", "open", "business"], []),
    ("🈵", ["japanese", "no", "vacancy"], []),

    # Geometric
    ("🔴", ["red", "circle", "round"], []),
    ("🟠", ["orange", "circle", "round"], []),
    ("🟡", ["yellow", "circle", "round"], []),
    ("🟢", ["green", "circle", "round"], []),
    ("🔵", ["blue", "circle", "round"], []),
    ("🟣", ["purple", "circle", "round"], []),
    ("🟤", ["brown", "circle", "round"], []),
    ("⚫", ["black", "circle", "round"], []),
    ("⚪", ["white", "circle", "round"], []),
    ("🟥", ["red", "square", "block"], []),
    ("🟧", ["orange", "square", "block"], []),
    ("🟨", ["yellow", "square", "block"], []),
    ("🟩", ["green", "square", "block"], []),
    ("🟦", ["blue", "square", "block"], []),
    ("🟪", ["purple", "square", "block"], []),
    ("🟫", ["brown", "square", "block"], []),
    ("⬛", ["black", "large", "square"], []),
    ("⬜", ["white", "large", "square"], []),
    ("◼️", ["black", "medium", "square"], []),
    ("◻️", ["white", "medium", "square"], []),
    ("◾", ["black", "medium-small", "square"], []),
    ("◽", ["white", "medium-small", "square"], []),
    ("▪️", ["black", "small", "square"], []),
    ("▫️", ["white", "small", "square"], []),
    ("🔶", ["large", "orange", "diamond"], []),
    ("🔷", ["large", "blue", "diamond"], []),
    ("🔸", ["small", "orange", "diamond"], []),
    ("🔹", ["small", "blue", "diamond"], []),
    ("🔺", ["red", "triangle", "pointed", "up"], []),
    ("🔻", ["red", "triangle", "pointed", "down"], []),
    ("💠", ["diamond", "shape", "flower"], []),
    ("🔘", ["radio", "button", "input"], []),
    ("🔳", ["white", "square", "button"], []),
    ("🔲", ["black", "square", "button"], []),
]

# Flags
FLAGS = [
    ("🏁", ["chequered", "flag", "racing"], []),
    ("🚩", ["triangular", "flag", "post"], []),
    ("🎌", ["crossed", "flags", "japanese"], []),
    ("🏴", ["black", "flag", "waving"], []),
    ("🏳️", ["white", "flag", "surrender"], []),
    ("🏳️‍🌈", ["rainbow", "flag", "pride"], []),
    ("🏳️‍⚧️", ["transgender", "flag", "pride"], []),
    ("🏴‍☠️", ["pirate", "flag", "jolly", "roger"], []),
    # Country flags (selected major ones)
    ("🇺🇳", ["united", "nations", "flag", "un"], []),
    ("🇺🇸", ["united", "states", "flag", "usa"], []),
    ("🇬🇧", ["united", "kingdom", "flag", "uk"], []),
    ("🇨🇦", ["canada", "flag", "canadian"], []),
    ("🇩🇪", ["germany", "flag", "german"], []),
    ("🇫🇷", ["france", "flag", "french"], []),
    ("🇪🇸", ["spain", "flag", "spanish"], []),
    ("🇮🇹", ["italy", "flag", "italian"], []),
    ("🇯🇵", ["japan", "flag", "japanese"], []),
    ("🇨🇳", ["china", "flag", "chinese"], []),
    ("🇰🇷", ["south", "korea", "flag"], []),
    ("🇮🇳", ["india", "flag", "indian"], []),
    ("🇷🇺", ["russia", "flag", "russian"], []),
    ("🇧🇷", ["brazil", "flag", "brazilian"], []),
    ("🇦🇺", ["australia", "flag", "australian"], []),
    ("🇲🇽", ["mexico", "flag", "mexican"], []),
    ("🇦🇷", ["argentina", "flag", "argentinian"], []),
    ("🇿🇦", ["south", "africa", "flag"], []),
    ("🇪🇬", ["egypt", "flag", "egyptian"], []),
    ("🇸🇦", ["saudi", "arabia", "flag"], []),
    ("🇹🇷", ["turkey", "flag", "turkish"], []),
    ("🇸🇪", ["sweden", "flag", "swedish"], []),
    ("🇳🇴", ["norway", "flag", "norwegian"], []),
    ("🇩🇰", ["denmark", "flag", "danish"], []),
    ("🇫🇮", ["finland", "flag", "finnish"], []),
    ("🇳🇱", ["netherlands", "flag", "dutch"], []),
    ("🇧🇪", ["belgium", "flag", "belgian"], []),
    ("🇨🇭", ["switzerland", "flag", "swiss"], []),
    ("🇦🇹", ["austria", "flag", "austrian"], []),
    ("🇵🇱", ["poland", "flag", "polish"], []),
    ("🇺🇦", ["ukraine", "flag", "ukrainian"], []),
    ("🇬🇷", ["greece", "flag", "greek"], []),
    ("🇵🇹", ["portugal", "flag", "portuguese"], []),
    ("🇮🇪", ["ireland", "flag", "irish"], []),
    ("🇮🇱", ["israel", "flag", "israeli"], []),
    ("🇹🇭", ["thailand", "flag", "thai"], []),
    ("🇻🇳", ["vietnam", "flag", "vietnamese"], []),
    ("🇮🇩", ["indonesia", "flag", "indonesian"], []),
    ("🇵🇭", ["philippines", "flag", "filipino"], []),
    ("🇸🇬", ["singapore", "flag", "singaporean"], []),
    ("🇲🇾", ["malaysia", "flag", "malaysian"], []),
    ("🇳🇿", ["new", "zealand", "flag"], []),
]

# Combine all categories
ALL_EMOJI_DATA = (
    SMILEYS_AND_EMOTION +
    PEOPLE_AND_BODY +
    ANIMALS_AND_NATURE +
    FOOD_AND_DRINK +
    TRAVEL_AND_PLACES +
    ACTIVITIES +
    OBJECTS +
    SYMBOLS +
    FLAGS
)

# Category mapping for easy access
CATEGORIES = {
    "Smileys & Emotion": SMILEYS_AND_EMOTION,
    "People & Body": PEOPLE_AND_BODY,
    "Animals & Nature": ANIMALS_AND_NATURE,
    "Food & Drink": FOOD_AND_DRINK,
    "Travel & Places": TRAVEL_AND_PLACES,
    "Activities": ACTIVITIES,
    "Objects": OBJECTS,
    "Symbols": SYMBOLS,
    "Flags": FLAGS,
}

# Total count
TOTAL_EMOJI_COUNT = len(ALL_EMOJI_DATA)
