# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import call_pb2 as call__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in call_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CallServiceStub(object):
    """CallService handles WebRTC call sessions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/call.CallService/CreateSession',
                request_serializer=call__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=call__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.CreateOffer = channel.unary_unary(
                '/call.CallService/CreateOffer',
                request_serializer=call__pb2.CreateOfferRequest.SerializeToString,
                response_deserializer=call__pb2.SDPResponse.FromString,
                _registered_method=True)
        self.CreateAnswer = channel.unary_unary(
                '/call.CallService/CreateAnswer',
                request_serializer=call__pb2.CreateAnswerRequest.SerializeToString,
                response_deserializer=call__pb2.SDPResponse.FromString,
                _registered_method=True)
        self.SetRemoteDescription = channel.unary_unary(
                '/call.CallService/SetRemoteDescription',
                request_serializer=call__pb2.SetRemoteDescriptionRequest.SerializeToString,
                response_deserializer=call__pb2.Empty.FromString,
                _registered_method=True)
        self.AddICECandidate = channel.unary_unary(
                '/call.CallService/AddICECandidate',
                request_serializer=call__pb2.AddICECandidateRequest.SerializeToString,
                response_deserializer=call__pb2.Empty.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/call.CallService/EndSession',
                request_serializer=call__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=call__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/call.CallService/StreamEvents',
                request_serializer=call__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=call__pb2.CallEvent.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/call.CallService/Heartbeat',
                request_serializer=call__pb2.Empty.SerializeToString,
                response_deserializer=call__pb2.Empty.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/call.CallService/Shutdown',
                request_serializer=call__pb2.Empty.SerializeToString,
                response_deserializer=call__pb2.Empty.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/call.CallService/GetStats',
                request_serializer=call__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=call__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.ListAudioDevices = channel.unary_unary(
                '/call.CallService/ListAudioDevices',
                request_serializer=call__pb2.Empty.SerializeToString,
                response_deserializer=call__pb2.ListAudioDevicesResponse.FromString,
                _registered_method=True)


class CallServiceServicer(object):
    """CallService handles WebRTC call sessions
    """

    def CreateSession(self, request, context):
        """Create a new call session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOffer(self, request, context):
        """Create SDP offer for outgoing call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAnswer(self, request, context):
        """Create SDP answer for incoming call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRemoteDescription(self, request, context):
        """Set remote SDP description (for outgoing calls after receiving session-accept)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddICECandidate(self, request, context):
        """Add ICE candidate to session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """End call session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Stream events from Go to Python (ICE candidates, state changes, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat to keep Go service alive (Python calls every 5s)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Graceful shutdown - Python tells Go to exit immediately
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get call statistics for a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAudioDevices(self, request, context):
        """List available audio devices
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=call__pb2.CreateSessionRequest.FromString,
                    response_serializer=call__pb2.CreateSessionResponse.SerializeToString,
            ),
            'CreateOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOffer,
                    request_deserializer=call__pb2.CreateOfferRequest.FromString,
                    response_serializer=call__pb2.SDPResponse.SerializeToString,
            ),
            'CreateAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAnswer,
                    request_deserializer=call__pb2.CreateAnswerRequest.FromString,
                    response_serializer=call__pb2.SDPResponse.SerializeToString,
            ),
            'SetRemoteDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRemoteDescription,
                    request_deserializer=call__pb2.SetRemoteDescriptionRequest.FromString,
                    response_serializer=call__pb2.Empty.SerializeToString,
            ),
            'AddICECandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.AddICECandidate,
                    request_deserializer=call__pb2.AddICECandidateRequest.FromString,
                    response_serializer=call__pb2.Empty.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=call__pb2.EndSessionRequest.FromString,
                    response_serializer=call__pb2.Empty.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=call__pb2.StreamEventsRequest.FromString,
                    response_serializer=call__pb2.CallEvent.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=call__pb2.Empty.FromString,
                    response_serializer=call__pb2.Empty.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=call__pb2.Empty.FromString,
                    response_serializer=call__pb2.Empty.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=call__pb2.GetStatsRequest.FromString,
                    response_serializer=call__pb2.GetStatsResponse.SerializeToString,
            ),
            'ListAudioDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAudioDevices,
                    request_deserializer=call__pb2.Empty.FromString,
                    response_serializer=call__pb2.ListAudioDevicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'call.CallService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('call.CallService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CallService(object):
    """CallService handles WebRTC call sessions
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/CreateSession',
            call__pb2.CreateSessionRequest.SerializeToString,
            call__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/CreateOffer',
            call__pb2.CreateOfferRequest.SerializeToString,
            call__pb2.SDPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/CreateAnswer',
            call__pb2.CreateAnswerRequest.SerializeToString,
            call__pb2.SDPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRemoteDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/SetRemoteDescription',
            call__pb2.SetRemoteDescriptionRequest.SerializeToString,
            call__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddICECandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/AddICECandidate',
            call__pb2.AddICECandidateRequest.SerializeToString,
            call__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/EndSession',
            call__pb2.EndSessionRequest.SerializeToString,
            call__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/call.CallService/StreamEvents',
            call__pb2.StreamEventsRequest.SerializeToString,
            call__pb2.CallEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/Heartbeat',
            call__pb2.Empty.SerializeToString,
            call__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/Shutdown',
            call__pb2.Empty.SerializeToString,
            call__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/GetStats',
            call__pb2.GetStatsRequest.SerializeToString,
            call__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAudioDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/call.CallService/ListAudioDevices',
            call__pb2.Empty.SerializeToString,
            call__pb2.ListAudioDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
