// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/call.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionStateEvent_State int32

const (
	ConnectionStateEvent_NEW          ConnectionStateEvent_State = 0
	ConnectionStateEvent_CHECKING     ConnectionStateEvent_State = 1
	ConnectionStateEvent_CONNECTED    ConnectionStateEvent_State = 2
	ConnectionStateEvent_COMPLETED    ConnectionStateEvent_State = 3
	ConnectionStateEvent_FAILED       ConnectionStateEvent_State = 4
	ConnectionStateEvent_DISCONNECTED ConnectionStateEvent_State = 5
	ConnectionStateEvent_CLOSED       ConnectionStateEvent_State = 6
)

// Enum value maps for ConnectionStateEvent_State.
var (
	ConnectionStateEvent_State_name = map[int32]string{
		0: "NEW",
		1: "CHECKING",
		2: "CONNECTED",
		3: "COMPLETED",
		4: "FAILED",
		5: "DISCONNECTED",
		6: "CLOSED",
	}
	ConnectionStateEvent_State_value = map[string]int32{
		"NEW":          0,
		"CHECKING":     1,
		"CONNECTED":    2,
		"COMPLETED":    3,
		"FAILED":       4,
		"DISCONNECTED": 5,
		"CLOSED":       6,
	}
)

func (x ConnectionStateEvent_State) Enum() *ConnectionStateEvent_State {
	p := new(ConnectionStateEvent_State)
	*p = x
	return p
}

func (x ConnectionStateEvent_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionStateEvent_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_call_proto_enumTypes[0].Descriptor()
}

func (ConnectionStateEvent_State) Type() protoreflect.EnumType {
	return &file_proto_call_proto_enumTypes[0]
}

func (x ConnectionStateEvent_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionStateEvent_State.Descriptor instead.
func (ConnectionStateEvent_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{12, 0}
}

type CreateSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PeerJid          string                 `protobuf:"bytes,2,opt,name=peer_jid,json=peerJid,proto3" json:"peer_jid,omitempty"`
	MicrophoneDevice string                 `protobuf:"bytes,3,opt,name=microphone_device,json=microphoneDevice,proto3" json:"microphone_device,omitempty"` // Device name (e.g., "alsa_input.pci-0000_05_00.6.analog-stereo"), empty = default
	SpeakersDevice   string                 `protobuf:"bytes,4,opt,name=speakers_device,json=speakersDevice,proto3" json:"speakers_device,omitempty"`       // Device name (e.g., "alsa_output.pci-0000_05_00.6.analog-stereo"), empty = default
	// Proxy configuration (for routing TURN connections through SOCKS5/HTTP proxy)
	ProxyHost     string `protobuf:"bytes,5,opt,name=proxy_host,json=proxyHost,proto3" json:"proxy_host,omitempty"`             // Proxy hostname/IP, empty = no proxy
	ProxyPort     int32  `protobuf:"varint,6,opt,name=proxy_port,json=proxyPort,proto3" json:"proxy_port,omitempty"`            // Proxy port (e.g., 9050 for Tor, 3128 for HTTP proxy)
	ProxyUsername string `protobuf:"bytes,7,opt,name=proxy_username,json=proxyUsername,proto3" json:"proxy_username,omitempty"` // Proxy authentication username (optional)
	ProxyPassword string `protobuf:"bytes,8,opt,name=proxy_password,json=proxyPassword,proto3" json:"proxy_password,omitempty"` // Proxy authentication password (optional)
	ProxyType     string `protobuf:"bytes,9,opt,name=proxy_type,json=proxyType,proto3" json:"proxy_type,omitempty"`             // "SOCKS5" or "HTTP", empty = no proxy
	// TURN server configuration (for relay mode)
	TurnServer   string `protobuf:"bytes,10,opt,name=turn_server,json=turnServer,proto3" json:"turn_server,omitempty"`       // TURN server URL (e.g., "turn:turn.example.com:3478"), empty = use default
	TurnUsername string `protobuf:"bytes,11,opt,name=turn_username,json=turnUsername,proto3" json:"turn_username,omitempty"` // TURN authentication username (optional)
	TurnPassword string `protobuf:"bytes,12,opt,name=turn_password,json=turnPassword,proto3" json:"turn_password,omitempty"` // TURN authentication password (optional)
	// ICE transport policy
	RelayOnly bool `protobuf:"varint,13,opt,name=relay_only,json=relayOnly,proto3" json:"relay_only,omitempty"` // If true, force relay-only mode (no P2P, privacy-first), default: true
	// Audio processing (WebRTC DSP)
	EchoCancel            bool  `protobuf:"varint,14,opt,name=echo_cancel,json=echoCancel,proto3" json:"echo_cancel,omitempty"`                                    // Enable echo cancellation, default: true
	EchoSuppressionLevel  int32 `protobuf:"varint,15,opt,name=echo_suppression_level,json=echoSuppressionLevel,proto3" json:"echo_suppression_level,omitempty"`    // 0=low, 1=moderate, 2=high, default: 1
	NoiseSuppression      bool  `protobuf:"varint,16,opt,name=noise_suppression,json=noiseSuppression,proto3" json:"noise_suppression,omitempty"`                  // Enable noise suppression, default: true
	NoiseSuppressionLevel int32 `protobuf:"varint,17,opt,name=noise_suppression_level,json=noiseSuppressionLevel,proto3" json:"noise_suppression_level,omitempty"` // 0=low, 1=moderate, 2=high, 3=very-high, default: 1
	GainControl           bool  `protobuf:"varint,18,opt,name=gain_control,json=gainControl,proto3" json:"gain_control,omitempty"`                                 // Enable automatic gain control, default: true
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_call_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetPeerJid() string {
	if x != nil {
		return x.PeerJid
	}
	return ""
}

func (x *CreateSessionRequest) GetMicrophoneDevice() string {
	if x != nil {
		return x.MicrophoneDevice
	}
	return ""
}

func (x *CreateSessionRequest) GetSpeakersDevice() string {
	if x != nil {
		return x.SpeakersDevice
	}
	return ""
}

func (x *CreateSessionRequest) GetProxyHost() string {
	if x != nil {
		return x.ProxyHost
	}
	return ""
}

func (x *CreateSessionRequest) GetProxyPort() int32 {
	if x != nil {
		return x.ProxyPort
	}
	return 0
}

func (x *CreateSessionRequest) GetProxyUsername() string {
	if x != nil {
		return x.ProxyUsername
	}
	return ""
}

func (x *CreateSessionRequest) GetProxyPassword() string {
	if x != nil {
		return x.ProxyPassword
	}
	return ""
}

func (x *CreateSessionRequest) GetProxyType() string {
	if x != nil {
		return x.ProxyType
	}
	return ""
}

func (x *CreateSessionRequest) GetTurnServer() string {
	if x != nil {
		return x.TurnServer
	}
	return ""
}

func (x *CreateSessionRequest) GetTurnUsername() string {
	if x != nil {
		return x.TurnUsername
	}
	return ""
}

func (x *CreateSessionRequest) GetTurnPassword() string {
	if x != nil {
		return x.TurnPassword
	}
	return ""
}

func (x *CreateSessionRequest) GetRelayOnly() bool {
	if x != nil {
		return x.RelayOnly
	}
	return false
}

func (x *CreateSessionRequest) GetEchoCancel() bool {
	if x != nil {
		return x.EchoCancel
	}
	return false
}

func (x *CreateSessionRequest) GetEchoSuppressionLevel() int32 {
	if x != nil {
		return x.EchoSuppressionLevel
	}
	return 0
}

func (x *CreateSessionRequest) GetNoiseSuppression() bool {
	if x != nil {
		return x.NoiseSuppression
	}
	return false
}

func (x *CreateSessionRequest) GetNoiseSuppressionLevel() int32 {
	if x != nil {
		return x.NoiseSuppressionLevel
	}
	return 0
}

func (x *CreateSessionRequest) GetGainControl() bool {
	if x != nil {
		return x.GainControl
	}
	return false
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_call_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferRequest) Reset() {
	*x = CreateOfferRequest{}
	mi := &file_proto_call_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferRequest) ProtoMessage() {}

func (x *CreateOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOfferRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RemoteSdp     string                 `protobuf:"bytes,2,opt,name=remote_sdp,json=remoteSdp,proto3" json:"remote_sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnswerRequest) Reset() {
	*x = CreateAnswerRequest{}
	mi := &file_proto_call_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnswerRequest) ProtoMessage() {}

func (x *CreateAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnswerRequest.ProtoReflect.Descriptor instead.
func (*CreateAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAnswerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateAnswerRequest) GetRemoteSdp() string {
	if x != nil {
		return x.RemoteSdp
	}
	return ""
}

type SDPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SDPResponse) Reset() {
	*x = SDPResponse{}
	mi := &file_proto_call_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SDPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDPResponse) ProtoMessage() {}

func (x *SDPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDPResponse.ProtoReflect.Descriptor instead.
func (*SDPResponse) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{4}
}

func (x *SDPResponse) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *SDPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetRemoteDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RemoteSdp     string                 `protobuf:"bytes,2,opt,name=remote_sdp,json=remoteSdp,proto3" json:"remote_sdp,omitempty"`
	SdpType       string                 `protobuf:"bytes,3,opt,name=sdp_type,json=sdpType,proto3" json:"sdp_type,omitempty"` // "offer" or "answer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRemoteDescriptionRequest) Reset() {
	*x = SetRemoteDescriptionRequest{}
	mi := &file_proto_call_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoteDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoteDescriptionRequest) ProtoMessage() {}

func (x *SetRemoteDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoteDescriptionRequest.ProtoReflect.Descriptor instead.
func (*SetRemoteDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{5}
}

func (x *SetRemoteDescriptionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetRemoteDescriptionRequest) GetRemoteSdp() string {
	if x != nil {
		return x.RemoteSdp
	}
	return ""
}

func (x *SetRemoteDescriptionRequest) GetSdpType() string {
	if x != nil {
		return x.SdpType
	}
	return ""
}

type AddICECandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Candidate     string                 `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string                 `protobuf:"bytes,3,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex int32                  `protobuf:"varint,4,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddICECandidateRequest) Reset() {
	*x = AddICECandidateRequest{}
	mi := &file_proto_call_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddICECandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddICECandidateRequest) ProtoMessage() {}

func (x *AddICECandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddICECandidateRequest.ProtoReflect.Descriptor instead.
func (*AddICECandidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{6}
}

func (x *AddICECandidateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddICECandidateRequest) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *AddICECandidateRequest) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *AddICECandidateRequest) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_proto_call_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{7}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_call_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{8}
}

func (x *StreamEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_call_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{9}
}

type CallEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*CallEvent_IceCandidate
	//	*CallEvent_ConnectionState
	//	*CallEvent_Error
	Event         isCallEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEvent) Reset() {
	*x = CallEvent{}
	mi := &file_proto_call_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEvent) ProtoMessage() {}

func (x *CallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEvent.ProtoReflect.Descriptor instead.
func (*CallEvent) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{10}
}

func (x *CallEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CallEvent) GetEvent() isCallEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CallEvent) GetIceCandidate() *ICECandidateEvent {
	if x != nil {
		if x, ok := x.Event.(*CallEvent_IceCandidate); ok {
			return x.IceCandidate
		}
	}
	return nil
}

func (x *CallEvent) GetConnectionState() *ConnectionStateEvent {
	if x != nil {
		if x, ok := x.Event.(*CallEvent_ConnectionState); ok {
			return x.ConnectionState
		}
	}
	return nil
}

func (x *CallEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*CallEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCallEvent_Event interface {
	isCallEvent_Event()
}

type CallEvent_IceCandidate struct {
	IceCandidate *ICECandidateEvent `protobuf:"bytes,2,opt,name=ice_candidate,json=iceCandidate,proto3,oneof"`
}

type CallEvent_ConnectionState struct {
	ConnectionState *ConnectionStateEvent `protobuf:"bytes,3,opt,name=connection_state,json=connectionState,proto3,oneof"`
}

type CallEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*CallEvent_IceCandidate) isCallEvent_Event() {}

func (*CallEvent_ConnectionState) isCallEvent_Event() {}

func (*CallEvent_Error) isCallEvent_Event() {}

type ICECandidateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex int32                  `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICECandidateEvent) Reset() {
	*x = ICECandidateEvent{}
	mi := &file_proto_call_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidateEvent) ProtoMessage() {}

func (x *ICECandidateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidateEvent.ProtoReflect.Descriptor instead.
func (*ICECandidateEvent) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{11}
}

func (x *ICECandidateEvent) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *ICECandidateEvent) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *ICECandidateEvent) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

type ConnectionStateEvent struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	State         ConnectionStateEvent_State `protobuf:"varint,1,opt,name=state,proto3,enum=call.ConnectionStateEvent_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStateEvent) Reset() {
	*x = ConnectionStateEvent{}
	mi := &file_proto_call_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStateEvent) ProtoMessage() {}

func (x *ConnectionStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStateEvent.ProtoReflect.Descriptor instead.
func (*ConnectionStateEvent) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{12}
}

func (x *ConnectionStateEvent) GetState() ConnectionStateEvent_State {
	if x != nil {
		return x.State
	}
	return ConnectionStateEvent_NEW
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_call_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_call_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConnectionState    string                 `protobuf:"bytes,1,opt,name=connection_state,json=connectionState,proto3" json:"connection_state,omitempty"`
	IceConnectionState string                 `protobuf:"bytes,2,opt,name=ice_connection_state,json=iceConnectionState,proto3" json:"ice_connection_state,omitempty"`
	IceGatheringState  string                 `protobuf:"bytes,3,opt,name=ice_gathering_state,json=iceGatheringState,proto3" json:"ice_gathering_state,omitempty"`
	BytesSent          int64                  `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived      int64                  `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	BandwidthKbps      int64                  `protobuf:"varint,6,opt,name=bandwidth_kbps,json=bandwidthKbps,proto3" json:"bandwidth_kbps,omitempty"`         // Current bandwidth in Kbps (updated every 2s)
	LocalCandidates    []string               `protobuf:"bytes,7,rep,name=local_candidates,json=localCandidates,proto3" json:"local_candidates,omitempty"`    // List of local IPs (host, srflx, relay)
	RemoteCandidates   []string               `protobuf:"bytes,8,rep,name=remote_candidates,json=remoteCandidates,proto3" json:"remote_candidates,omitempty"` // List of remote IPs
	ConnectionType     string                 `protobuf:"bytes,9,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`       // "P2P (direct)", "P2P (srflx)", "TURN relay", etc.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_call_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatsResponse) GetConnectionState() string {
	if x != nil {
		return x.ConnectionState
	}
	return ""
}

func (x *GetStatsResponse) GetIceConnectionState() string {
	if x != nil {
		return x.IceConnectionState
	}
	return ""
}

func (x *GetStatsResponse) GetIceGatheringState() string {
	if x != nil {
		return x.IceGatheringState
	}
	return ""
}

func (x *GetStatsResponse) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *GetStatsResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *GetStatsResponse) GetBandwidthKbps() int64 {
	if x != nil {
		return x.BandwidthKbps
	}
	return 0
}

func (x *GetStatsResponse) GetLocalCandidates() []string {
	if x != nil {
		return x.LocalCandidates
	}
	return nil
}

func (x *GetStatsResponse) GetRemoteCandidates() []string {
	if x != nil {
		return x.RemoteCandidates
	}
	return nil
}

func (x *GetStatsResponse) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

type AudioDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // Internal device ID (e.g., "alsa_output.pci-0000_05_00.6.analog-stereo")
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                    // User-friendly name (e.g., "Family 17h/19h/1ah HD Audio Controller Analog Stereo")
	DeviceClass   string                 `protobuf:"bytes,3,opt,name=device_class,json=deviceClass,proto3" json:"device_class,omitempty"` // "Audio/Source" (microphone) or "Audio/Sink" (speakers)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDevice) Reset() {
	*x = AudioDevice{}
	mi := &file_proto_call_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDevice) ProtoMessage() {}

func (x *AudioDevice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDevice.ProtoReflect.Descriptor instead.
func (*AudioDevice) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{16}
}

func (x *AudioDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudioDevice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AudioDevice) GetDeviceClass() string {
	if x != nil {
		return x.DeviceClass
	}
	return ""
}

type ListAudioDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*AudioDevice         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAudioDevicesResponse) Reset() {
	*x = ListAudioDevicesResponse{}
	mi := &file_proto_call_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAudioDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAudioDevicesResponse) ProtoMessage() {}

func (x *ListAudioDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAudioDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListAudioDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{17}
}

func (x *ListAudioDevicesResponse) GetDevices() []*AudioDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SetMuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Muted         bool                   `protobuf:"varint,2,opt,name=muted,proto3" json:"muted,omitempty"` // true = mute microphone, false = unmute
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMuteRequest) Reset() {
	*x = SetMuteRequest{}
	mi := &file_proto_call_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMuteRequest) ProtoMessage() {}

func (x *SetMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_call_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMuteRequest.ProtoReflect.Descriptor instead.
func (*SetMuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_call_proto_rawDescGZIP(), []int{18}
}

func (x *SetMuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetMuteRequest) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

var File_proto_call_proto protoreflect.FileDescriptor

const file_proto_call_proto_rawDesc = "" +
	"\n" +
	"\x10proto/call.proto\x12\x04call\"\xba\x05\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bpeer_jid\x18\x02 \x01(\tR\apeerJid\x12+\n" +
	"\x11microphone_device\x18\x03 \x01(\tR\x10microphoneDevice\x12'\n" +
	"\x0fspeakers_device\x18\x04 \x01(\tR\x0espeakersDevice\x12\x1d\n" +
	"\n" +
	"proxy_host\x18\x05 \x01(\tR\tproxyHost\x12\x1d\n" +
	"\n" +
	"proxy_port\x18\x06 \x01(\x05R\tproxyPort\x12%\n" +
	"\x0eproxy_username\x18\a \x01(\tR\rproxyUsername\x12%\n" +
	"\x0eproxy_password\x18\b \x01(\tR\rproxyPassword\x12\x1d\n" +
	"\n" +
	"proxy_type\x18\t \x01(\tR\tproxyType\x12\x1f\n" +
	"\vturn_server\x18\n" +
	" \x01(\tR\n" +
	"turnServer\x12#\n" +
	"\rturn_username\x18\v \x01(\tR\fturnUsername\x12#\n" +
	"\rturn_password\x18\f \x01(\tR\fturnPassword\x12\x1d\n" +
	"\n" +
	"relay_only\x18\r \x01(\bR\trelayOnly\x12\x1f\n" +
	"\vecho_cancel\x18\x0e \x01(\bR\n" +
	"echoCancel\x124\n" +
	"\x16echo_suppression_level\x18\x0f \x01(\x05R\x14echoSuppressionLevel\x12+\n" +
	"\x11noise_suppression\x18\x10 \x01(\bR\x10noiseSuppression\x126\n" +
	"\x17noise_suppression_level\x18\x11 \x01(\x05R\x15noiseSuppressionLevel\x12!\n" +
	"\fgain_control\x18\x12 \x01(\bR\vgainControl\"G\n" +
	"\x15CreateSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"3\n" +
	"\x12CreateOfferRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"S\n" +
	"\x13CreateAnswerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"remote_sdp\x18\x02 \x01(\tR\tremoteSdp\"5\n" +
	"\vSDPResponse\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"v\n" +
	"\x1bSetRemoteDescriptionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"remote_sdp\x18\x02 \x01(\tR\tremoteSdp\x12\x19\n" +
	"\bsdp_type\x18\x03 \x01(\tR\asdpType\"\x96\x01\n" +
	"\x16AddICECandidateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x03 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x04 \x01(\x05R\rsdpMlineIndex\"2\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13StreamEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\a\n" +
	"\x05Empty\"\xe6\x01\n" +
	"\tCallEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\rice_candidate\x18\x02 \x01(\v2\x17.call.ICECandidateEventH\x00R\ficeCandidate\x12G\n" +
	"\x10connection_state\x18\x03 \x01(\v2\x1a.call.ConnectionStateEventH\x00R\x0fconnectionState\x12(\n" +
	"\x05error\x18\x04 \x01(\v2\x10.call.ErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\"r\n" +
	"\x11ICECandidateEvent\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\x05R\rsdpMlineIndex\"\xb6\x01\n" +
	"\x14ConnectionStateEvent\x126\n" +
	"\x05state\x18\x01 \x01(\x0e2 .call.ConnectionStateEvent.StateR\x05state\"f\n" +
	"\x05State\x12\a\n" +
	"\x03NEW\x10\x00\x12\f\n" +
	"\bCHECKING\x10\x01\x12\r\n" +
	"\tCONNECTED\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\x10\n" +
	"\fDISCONNECTED\x10\x05\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x06\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x0fGetStatsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x8d\x03\n" +
	"\x10GetStatsResponse\x12)\n" +
	"\x10connection_state\x18\x01 \x01(\tR\x0fconnectionState\x120\n" +
	"\x14ice_connection_state\x18\x02 \x01(\tR\x12iceConnectionState\x12.\n" +
	"\x13ice_gathering_state\x18\x03 \x01(\tR\x11iceGatheringState\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x03R\rbytesReceived\x12%\n" +
	"\x0ebandwidth_kbps\x18\x06 \x01(\x03R\rbandwidthKbps\x12)\n" +
	"\x10local_candidates\x18\a \x03(\tR\x0flocalCandidates\x12+\n" +
	"\x11remote_candidates\x18\b \x03(\tR\x10remoteCandidates\x12'\n" +
	"\x0fconnection_type\x18\t \x01(\tR\x0econnectionType\"f\n" +
	"\vAudioDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fdevice_class\x18\x03 \x01(\tR\vdeviceClass\"G\n" +
	"\x18ListAudioDevicesResponse\x12+\n" +
	"\adevices\x18\x01 \x03(\v2\x11.call.AudioDeviceR\adevices\"E\n" +
	"\x0eSetMuteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05muted\x18\x02 \x01(\bR\x05muted2\xc0\x05\n" +
	"\vCallService\x12H\n" +
	"\rCreateSession\x12\x1a.call.CreateSessionRequest\x1a\x1b.call.CreateSessionResponse\x12:\n" +
	"\vCreateOffer\x12\x18.call.CreateOfferRequest\x1a\x11.call.SDPResponse\x12<\n" +
	"\fCreateAnswer\x12\x19.call.CreateAnswerRequest\x1a\x11.call.SDPResponse\x12F\n" +
	"\x14SetRemoteDescription\x12!.call.SetRemoteDescriptionRequest\x1a\v.call.Empty\x12<\n" +
	"\x0fAddICECandidate\x12\x1c.call.AddICECandidateRequest\x1a\v.call.Empty\x122\n" +
	"\n" +
	"EndSession\x12\x17.call.EndSessionRequest\x1a\v.call.Empty\x12<\n" +
	"\fStreamEvents\x12\x19.call.StreamEventsRequest\x1a\x0f.call.CallEvent0\x01\x12%\n" +
	"\tHeartbeat\x12\v.call.Empty\x1a\v.call.Empty\x12$\n" +
	"\bShutdown\x12\v.call.Empty\x1a\v.call.Empty\x129\n" +
	"\bGetStats\x12\x15.call.GetStatsRequest\x1a\x16.call.GetStatsResponse\x12?\n" +
	"\x10ListAudioDevices\x12\v.call.Empty\x1a\x1e.call.ListAudioDevicesResponse\x12,\n" +
	"\aSetMute\x12\x14.call.SetMuteRequest\x1a\v.call.EmptyB2Z0github.com/yourusername/drunk-call-service/protob\x06proto3"

var (
	file_proto_call_proto_rawDescOnce sync.Once
	file_proto_call_proto_rawDescData []byte
)

func file_proto_call_proto_rawDescGZIP() []byte {
	file_proto_call_proto_rawDescOnce.Do(func() {
		file_proto_call_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_call_proto_rawDesc), len(file_proto_call_proto_rawDesc)))
	})
	return file_proto_call_proto_rawDescData
}

var file_proto_call_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_call_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_call_proto_goTypes = []any{
	(ConnectionStateEvent_State)(0),     // 0: call.ConnectionStateEvent.State
	(*CreateSessionRequest)(nil),        // 1: call.CreateSessionRequest
	(*CreateSessionResponse)(nil),       // 2: call.CreateSessionResponse
	(*CreateOfferRequest)(nil),          // 3: call.CreateOfferRequest
	(*CreateAnswerRequest)(nil),         // 4: call.CreateAnswerRequest
	(*SDPResponse)(nil),                 // 5: call.SDPResponse
	(*SetRemoteDescriptionRequest)(nil), // 6: call.SetRemoteDescriptionRequest
	(*AddICECandidateRequest)(nil),      // 7: call.AddICECandidateRequest
	(*EndSessionRequest)(nil),           // 8: call.EndSessionRequest
	(*StreamEventsRequest)(nil),         // 9: call.StreamEventsRequest
	(*Empty)(nil),                       // 10: call.Empty
	(*CallEvent)(nil),                   // 11: call.CallEvent
	(*ICECandidateEvent)(nil),           // 12: call.ICECandidateEvent
	(*ConnectionStateEvent)(nil),        // 13: call.ConnectionStateEvent
	(*ErrorEvent)(nil),                  // 14: call.ErrorEvent
	(*GetStatsRequest)(nil),             // 15: call.GetStatsRequest
	(*GetStatsResponse)(nil),            // 16: call.GetStatsResponse
	(*AudioDevice)(nil),                 // 17: call.AudioDevice
	(*ListAudioDevicesResponse)(nil),    // 18: call.ListAudioDevicesResponse
	(*SetMuteRequest)(nil),              // 19: call.SetMuteRequest
}
var file_proto_call_proto_depIdxs = []int32{
	12, // 0: call.CallEvent.ice_candidate:type_name -> call.ICECandidateEvent
	13, // 1: call.CallEvent.connection_state:type_name -> call.ConnectionStateEvent
	14, // 2: call.CallEvent.error:type_name -> call.ErrorEvent
	0,  // 3: call.ConnectionStateEvent.state:type_name -> call.ConnectionStateEvent.State
	17, // 4: call.ListAudioDevicesResponse.devices:type_name -> call.AudioDevice
	1,  // 5: call.CallService.CreateSession:input_type -> call.CreateSessionRequest
	3,  // 6: call.CallService.CreateOffer:input_type -> call.CreateOfferRequest
	4,  // 7: call.CallService.CreateAnswer:input_type -> call.CreateAnswerRequest
	6,  // 8: call.CallService.SetRemoteDescription:input_type -> call.SetRemoteDescriptionRequest
	7,  // 9: call.CallService.AddICECandidate:input_type -> call.AddICECandidateRequest
	8,  // 10: call.CallService.EndSession:input_type -> call.EndSessionRequest
	9,  // 11: call.CallService.StreamEvents:input_type -> call.StreamEventsRequest
	10, // 12: call.CallService.Heartbeat:input_type -> call.Empty
	10, // 13: call.CallService.Shutdown:input_type -> call.Empty
	15, // 14: call.CallService.GetStats:input_type -> call.GetStatsRequest
	10, // 15: call.CallService.ListAudioDevices:input_type -> call.Empty
	19, // 16: call.CallService.SetMute:input_type -> call.SetMuteRequest
	2,  // 17: call.CallService.CreateSession:output_type -> call.CreateSessionResponse
	5,  // 18: call.CallService.CreateOffer:output_type -> call.SDPResponse
	5,  // 19: call.CallService.CreateAnswer:output_type -> call.SDPResponse
	10, // 20: call.CallService.SetRemoteDescription:output_type -> call.Empty
	10, // 21: call.CallService.AddICECandidate:output_type -> call.Empty
	10, // 22: call.CallService.EndSession:output_type -> call.Empty
	11, // 23: call.CallService.StreamEvents:output_type -> call.CallEvent
	10, // 24: call.CallService.Heartbeat:output_type -> call.Empty
	10, // 25: call.CallService.Shutdown:output_type -> call.Empty
	16, // 26: call.CallService.GetStats:output_type -> call.GetStatsResponse
	18, // 27: call.CallService.ListAudioDevices:output_type -> call.ListAudioDevicesResponse
	10, // 28: call.CallService.SetMute:output_type -> call.Empty
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_call_proto_init() }
func file_proto_call_proto_init() {
	if File_proto_call_proto != nil {
		return
	}
	file_proto_call_proto_msgTypes[10].OneofWrappers = []any{
		(*CallEvent_IceCandidate)(nil),
		(*CallEvent_ConnectionState)(nil),
		(*CallEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_call_proto_rawDesc), len(file_proto_call_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_call_proto_goTypes,
		DependencyIndexes: file_proto_call_proto_depIdxs,
		EnumInfos:         file_proto_call_proto_enumTypes,
		MessageInfos:      file_proto_call_proto_msgTypes,
	}.Build()
	File_proto_call_proto = out.File
	file_proto_call_proto_goTypes = nil
	file_proto_call_proto_depIdxs = nil
}
